/**
 * Shared DOM IIFEs + strips for M365 Copilot (generated by build-copilot-dom-modules.mjs).
 */
export const COMPOSER_ANCESTOR_CLOSEST =
  '#m365-chat-editor-target-element, [data-lexical-editor="true"], [role="textbox"][aria-label*="メッセージを送信"], [role="textbox"][aria-label*="Send a message"], [role="textbox"][aria-label*="Message"], [role="textbox"][aria-label*="message"], [role="textbox"][aria-label*="Copilot"]';

export const STREAMING_STOP_SELECTORS = [
  ".fai-SendButton__stopBackground",
  'button[aria-label*="生成を停止"]',
  'button[aria-label*="Stop generating"]',
  'button[aria-label*="Stop response"]',
  'button[aria-label*="停止"]',
  'button[data-testid="stopGeneratingButton"]',
  'button[data-testid*="stop"]',
  '[data-testid*="StopGenerating"]',
  '[class*="StopGenerating"]',
  '[class*="stopGenerating"]'
];

export const ASSISTANT_REPLY_DOM_SELECTORS = [
  /** M365 Copilot web (Fluent): narrow reply body; prefer over generic article/markdown hits. */
  '[data-testid="copilot-message-reply-div"]',
  '[class*="fai-CopilotMessage"]',
  '[data-testid="markdown-reply"]',
  '[data-testid*="message-content"]',
  '[data-testid*="message-body"]',
  '[data-testid*="assistant"]',
  '[data-message-author-role="assistant"]',
  'article[data-message-author-role="assistant"]',
  'div[data-message-type="Chat"]',
  '[role="article"]',
  ".markdown-body",
  ".fui-ChatMessageBody",
  '[class*="ChatMessage"]',
  '[class*="MessageBody"]',
  '[class*="message-body"]',
  "cib-message[type='response']",
  "cib-message .content",
  "cib-serp",
  "cib-rich-card"
];

export const M365_SUGGESTION_NOISE_SELECTORS = [
  ".fai-SuggestionList",
  ".fai-Suggestion",
  '[data-testid="chat-suggestion"]',
];

const M365_NOISY_REPLY_LINE_PATTERNS = [
  /^show less$/i,
  /^feedback$/i,
  /^provide your feedback on /i,
  /^copy code$/i,
  /^display options$/i,
  /^go to line(?:\s*\(ctrl\+g\))?$/i,
  /^more actions$/i,
  /^commercial data protection badge\.?$/i,
];

/** Strip M365 Copilot Web UI a11y chrome from innerText ("Copilot said:", branding line). */
function stripM365CopilotReplyChrome(text) {
  let s = String(text || "").trim();
  if (!s) return s;
  s = s.replace(/^Copilot said:\s*/i, "");
  s = s.replace(/^Copilot\s*(\n+|$)/im, "");
  s = s.replace(/^Copilot(?=\S)/i, "");
  const lines = s.split(/\r?\n/).map((line) => line.trim());
  const previousNonEmptyLine = (index) => {
    for (let i = index - 1; i >= 0; i -= 1) {
      if (lines[i]) return lines[i];
    }
    return "";
  };
  const nextNonEmptyLine = (index) => {
    for (let i = index + 1; i < lines.length; i += 1) {
      if (lines[i]) return lines[i];
    }
    return "";
  };
  const isLikelySourceLabelLine = (line) => {
    if (/^bing$/i.test(line)) return true;
    if (/^[a-z0-9][a-z0-9-]{2,31}$/i.test(line)) return true;
    return /^(?:[a-z0-9-]+\.)+(?:com|org|net|io|dev|ai|co|jp|us|uk)$/i.test(line);
  };
  const isLikelyCitationVoteLine = (line, index) => {
    if (!/^\+\d+$/.test(line)) return false;
    return isLikelySourceLabelLine(previousNonEmptyLine(index));
  };
  const isLikelyCodeStartLine = (line) => {
    if (!line) return false;
    return (
      /^<!doctype html>/i.test(line) ||
      /^<(?:html|head|body|style|script|main|div|section|canvas)\b/i.test(line) ||
      /^(?:const|let|var|function|class)\b/.test(line)
    );
  };
  const isLikelyCodeBadgeLine = (line, index) => {
    if (!line) return false;
    const next = nextNonEmptyLine(index);
    const prev = previousNonEmptyLine(index);
    if (/^show more lines$/i.test(line)) return true;
    if (/^show less$/i.test(line)) return true;
    if (/^reasoning completed in \d+ steps$/i.test(line)) return true;
    if (/^推論が\s*\d+\s*ステップで完了しました$/u.test(line)) return true;
    if (/^(?:get a quick answer|searches|retrying searches)$/i.test(line)) return true;
    if (
      /^(?:html|javascript|typescript|tsx|jsx|json|css|xml|yaml|sql|shell|bash|python|rust|markdown)$/i.test(line) &&
      isLikelyCodeStartLine(next)
    ) {
      return true;
    }
    if (/^cloud$/i.test(line) && (/^(?:html|javascript|typescript|json|css)$/i.test(next) || isLikelyCodeStartLine(next))) {
      return true;
    }
    if (/^[A-Z][A-Za-z0-9+.# -]{1,18}$/.test(line) && isLikelyCodeStartLine(next) && /^cloud$/i.test(prev)) {
      return true;
    }
    return false;
  };
  const filtered = lines.filter((line, index) => {
      if (!line) return true;
      if (/^copilot$/i.test(line)) return false;
      if (/^plain text$/i.test(line)) return false;
      if (/^sources?$/i.test(line)) return false;
      if (/^relay_tool isn.?t fully supported\./i.test(line)) return false;
      if (M365_NOISY_REPLY_LINE_PATTERNS.some((pattern) => pattern.test(line))) return false;
      if (isLikelyCodeBadgeLine(line, index)) return false;
      if (isLikelyCitationVoteLine(line, index)) return false;
      if (lineMatchesStreamingPlaceholder(line)) return false;
      if (isLikelySourceLabelLine(line) && /^\+\d+$/.test(nextNonEmptyLine(index))) {
        return false;
      }
      if (isLikelySourceLabelLine(line) && previousNonEmptyLine(index)) {
        const next = nextNonEmptyLine(index);
        if (!next || /^sources?$/i.test(next) || lineMatchesStreamingPlaceholder(next)) {
          return false;
        }
      }
      return true;
    });
  s = filtered.join("\n");
  return s.trim();
}

/** Last-line / tail matches while Copilot is still streaming (Stop button may not be visible yet). */
export const COPILOT_STREAMING_PLACEHOLDER_LAST_LINES = [
  "応答を生成しています",
  "応答を作成しています",
  "生成しています",
  "作成しています",
  "考えています",
  "処理しています",
  "しばらくお待ちください",
  "Generating response",
  "Creating response",
  "Please wait",
];

function normalizeStreamingLine(line) {
  return String(line || "")
    .replace(/\u2026/g, "...")
    .replace(/\u00a0/g, " ")
    .trim();
}

function lineMatchesStreamingPlaceholder(line) {
  const n = normalizeStreamingLine(line).toLowerCase();
  if (!n) return false;
  for (const p of COPILOT_STREAMING_PLACEHOLDER_LAST_LINES) {
    if (n === p.toLowerCase()) return true;
  }
  if (/^thinking[.\u2026…\s]*$/i.test(n)) return true;
  if (/^generating[.\u2026…\s]*$/i.test(n)) return true;
  return false;
}

function replyEndsWithStreamingPlaceholder(text) {
  const s = String(text || "").trimEnd();
  if (!s) return false;
  const parts = s.split(/\r?\n/);
  for (let i = parts.length - 1; i >= 0; i--) {
    const t = parts[i].trim();
    if (!t) continue;
    return lineMatchesStreamingPlaceholder(t);
  }
  return false;
}

/** Remove trailing placeholder lines Copilot appends to innerText during streaming. */
function stripStreamingPlaceholderTail(text) {
  let s = String(text || "");
  for (let guard = 0; guard < 48; guard++) {
    const lines = s.split(/\r?\n/);
    let lastIdx = lines.length - 1;
    while (lastIdx >= 0 && !lines[lastIdx].trim()) lastIdx--;
    if (lastIdx < 0) break;
    if (!lineMatchesStreamingPlaceholder(lines[lastIdx])) break;
    lines.splice(lastIdx, 1);
    s = lines.join("\n");
  }
  return s.trim();
}

function assistantTextHasStructuredContent(text) {
  const s = String(text || "");
  return (
    /```/.test(s) ||
    /^\s*(?:[-*]|\d+\.)\s+/m.test(s) ||
    /^\s*\|.+\|\s*$/m.test(s)
  );
}

function shouldPreferExpandedAssistantTurn(replyText, turnText) {
  const reply = stripStreamingPlaceholderTail(stripM365CopilotReplyChrome(replyText));
  const turn = stripStreamingPlaceholderTail(stripM365CopilotReplyChrome(turnText));
  if (!turn) return false;
  if (!reply) return true;
  const delta = turn.length - reply.length;
  if (delta < 20) return false;
  if (assistantTextHasStructuredContent(turn) && !assistantTextHasStructuredContent(reply)) {
    return true;
  }
  return delta >= Math.max(60, Math.floor(reply.length * 0.45));
}

export const RESPONSE_TIMEOUT_MS = 18e4;
/** Main loop sleep in waitForDomResponse (was 1000ms → ~3min wall time on phantom “generating”). */
export const RESPONSE_POLL_INTERVAL_MS = 500;
/** Consecutive polls with raw generating=true before treating “stop” UI as phantom (was 55 @ 1s ≈ 55s lost). */
export const RESPONSE_PHANTOM_GENERATING_POLLS = 22;
/** After DOM looks stable, pause before re-extract (was 2800ms). */
export const RESPONSE_POST_STABLE_MS = 1000;

export const CHATHUB_ASSISTANT_MIN_CHARS = 2;

function copilotDomGeneratingIifeExpression() {
  return `(() => {
    function reallyVisible(el) {
      if (!el || el.offsetParent === null) return false;
      const st = getComputedStyle(el);
      if (st.visibility === "hidden" || st.display === "none" || Number(st.opacity) === 0) return false;
      const r = el.getBoundingClientRect();
      if (r.width < 3 || r.height < 3) return false;
      return r.bottom > 2 && r.right > 2 && r.top < innerHeight - 2 && r.left < innerWidth - 2;
    }
    function walkElements(root, visit) {
      if (!root) return;
      if (root.nodeType === 1) visit(root);
      const tree = root.nodeType === 9 ? root.documentElement : root;
      if (!tree) return;
      const kids = tree.children || [];
      for (let i = 0; i < kids.length; i++) walkElements(kids[i], visit);
      if (tree.shadowRoot) walkElements(tree.shadowRoot, visit);
    }
    function queryDeepAll(selector, doc) {
      const top = doc?.nodeType === 9 ? (doc.documentElement || doc.body) : doc;
      if (!top) return [];
      const out = [];
      walkElements(top, (el) => {
        try {
          if (el.matches && el.matches(selector)) out.push(el);
        } catch (_) {}
      });
      return out;
    }
    function isGeneratingInDoc(doc) {
      const sels = ${JSON.stringify(STREAMING_STOP_SELECTORS)};
      for (const s of sels) {
        for (const el of queryDeepAll(s, doc)) {
          if (reallyVisible(el)) return true;
        }
      }
      for (const b of queryDeepAll("button, [role='button'], [role='menuitem']", doc)) {
        if (!reallyVisible(b)) continue;
        const a = (b.getAttribute("aria-label") || b.getAttribute("title") || "").toLowerCase();
        if (!a) continue;
        if (/\\bstop\\b/.test(a) && /generat|stream|response|応答|生成|回答|作成/.test(a)) return true;
        if (/\\bcancel\\b/.test(a) && /response|応答|生成|回答|stream/.test(a)) return true;
        if (
          /arrêt|arret|interromp|interrupt|detener|detén|abbrechen/.test(a) &&
          /génér|genér|generat|réponse|response|respuesta|stream|flux|応答|生成/.test(a)
        )
          return true;
      }
      return false;
    }
    function scanDocs(doc, depth) {
      if (isGeneratingInDoc(doc)) return true;
      if (depth > 8) return false;
      let frames;
      try {
        frames = doc.querySelectorAll("iframe");
      } catch (_) {
        return false;
      }
      for (const f of frames) {
        try {
          const c = f.contentDocument;
          if (c && scanDocs(c, depth + 1)) return true;
        } catch (_) {}
      }
      return false;
    }
    return scanDocs(document, 0);
  })()`;
}

async function isCopilotGenerating(session) {
  const r = await session.evaluate(copilotDomGeneratingIifeExpression()).catch(() => ({ value: false }));
  return r?.value === true;
}

/**
 * Prefer the outermost last assistant *turn*. Walks open shadow roots and same-origin iframes
 * (M365 often hosts the transcript in an embedded frame).
 */
function copilotDomReplyExtractIifeExpression() {
  return `(() => {
    const suggestionSelectors = ${JSON.stringify(M365_SUGGESTION_NOISE_SELECTORS)};
    function visible(el) {
      return el && el.offsetParent !== null;
    }
    function inComposer(el) {
      return !!(el && el.closest(${JSON.stringify(COMPOSER_ANCESTOR_CLOSEST)}));
    }
    /** User bubbles often match generic markdown/article selectors — never treat as assistant reply. */
    function inUserTurn(el) {
      if (!el) return false;
      try {
        if (el.closest('[data-message-author-role="user"]')) return true;
        if (el.closest('[data-message-author-role="User"]')) return true;
        if (el.closest('[data-testid="userMessage"]')) return true;
        if (el.closest('[data-testid*="user-message"]')) return true;
        if (el.closest('[data-testid*="UserMessage"]')) return true;
        if (el.matches && el.matches('cib-message[type="user"]')) return true;
        if (el.closest('[aria-label*="Your message"]')) return true;
        if (el.closest('[aria-label*="your message"]')) return true;
        if (el.closest('[aria-label*="送信した"]')) return true;
        if (el.closest('[aria-label*="自分のメッセージ"]')) return true;
        if (el.closest('[class*="fai-UserMessage"]')) return true;
        if (el.closest('[data-testid="chatQuestion"]')) return true;
      } catch (_) {}
      return false;
    }
    function nodeText(el) {
      if (!el) return "";
      let target = el;
      try {
        if (typeof el.cloneNode === "function") {
          target = el.cloneNode(true);
          const noisySelectors = [
            ".fai-CopilotMessage__footnote",
            ".fai-CopilotMessage__actions",
            ".scc-ChainOfThought",
            ".fai-SuggestionList",
            ".fai-Suggestion",
            ".fui-MessageBar",
            ".fai-Citation",
            ".fai-CitationCard",
            '[data-testid="chat-suggestion"]',
            '[data-citation-group-id]',
            '[data-grouped-citations]',
            '[data-testid="loading-message"]',
            '[data-testid="narrator-announcement"]',
            '[data-testid="sources-button-testid"]',
            '[data-testid*="source"]',
            '[data-testid*="Source"]',
            '[data-testid*="citation"]',
            '[data-testid*="Citation"]',
            '[data-testid="chat-response-message-disclaimer"]',
            '[data-testid="feedback-button-testid"]',
            '[data-testid="CopyButtonContainerTestId"]',
            '[data-testid="CopyButtonTestId"]',
            '[data-testid="overflow-menu-button"]',
            '[data-testid="SchedulePromptButtonTestId"]',
            '[data-testid="pages-split-button-primary"]',
            '[data-testid="pages-split-button-menu"]',
            '[data-testid="message-footer"]',
            '[data-testid="message-toolbar"]',
            '#language-badge',
            '#message-banner',
            '#go-to-line-button',
            '#copy-button',
            '#codeblock-footer',
            '[data-message-type="Progress"]',
            '[data-testid="message-bar-body-info"]',
            '[class*="Citation"]',
            '[class*="citation"]',
            '[class*="Source"]',
            '[class*="source"]',
            '[class*="Footnote"]',
            '[class*="footnote"]',
            '[class*="Feedback"]',
            '[class*="feedback"]',
            '[class*="Toolbar"]',
            '[class*="toolbar"]',
          ];
          for (const selector of noisySelectors) {
            for (const node of target.querySelectorAll(selector)) {
              node.remove();
            }
          }
          for (const node of target.querySelectorAll('button, [role="button"], [role="menuitem"], [role="progressbar"], [role="toolbar"]')) {
            node.remove();
          }
        }
      } catch (_) {}
      const t = (target.innerText || target.textContent || "").trim();
      return t;
    }
    function isSuggestionToolbar(el) {
      if (!el || !el.getAttribute) return false;
      const role = (el.getAttribute("role") || "").toLowerCase();
      if (role !== "toolbar") return false;
      const label = [
        el.getAttribute("aria-label") || "",
        el.getAttribute("title") || "",
      ].join(" ").toLowerCase();
      return /\\bsuggestions?\\b/.test(label);
    }
    function isSuggestionNode(el) {
      if (!el || !el.closest) return false;
      try {
        for (const selector of suggestionSelectors) {
          if (el.matches?.(selector) || el.closest(selector)) return true;
        }
        const toolbar = el.matches?.('[role="toolbar"]') ? el : el.closest('[role="toolbar"]');
        return !!toolbar && isSuggestionToolbar(toolbar);
      } catch (_) {
        return false;
      }
    }
    function hasSuggestionSurfaceOutsideReply(container, replyRoot) {
      if (!container || !container.querySelectorAll) return false;
      try {
        const candidates = container.querySelectorAll(
          suggestionSelectors.join(", ") + ', [role="toolbar"]'
        );
        for (const node of candidates) {
          if (!visible(node)) continue;
          if (replyRoot && replyRoot.contains(node)) continue;
          if (isSuggestionNode(node)) return true;
        }
      } catch (_) {}
      return false;
    }
    function proseNodeTextWithoutCodePreview(el) {
      if (!el) return "";
      let target = el;
      try {
        if (typeof el.cloneNode === "function") {
          target = el.cloneNode(true);
          for (const selector of [
            '[role="group"][aria-label="Code Preview"]',
            '.scriptor-component-code-block',
            '.scriptor-pageContainer',
            '.scriptor-code-editor',
          ]) {
            for (const node of target.querySelectorAll(selector)) {
              node.remove();
            }
          }
        }
      } catch (_) {}
      return nodeText(target);
    }
    function isNoisyReplyNode(el) {
      if (!el || !el.closest) return false;
      try {
        return !!el.closest([
          ".fai-CopilotMessage__actions",
          ".fai-CopilotMessage__footnote",
          ".fai-Citation",
          ".fai-CitationCard",
          ".fai-SuggestionList",
          '[data-testid*="source"]',
          '[data-testid*="Source"]',
          '[data-testid*="citation"]',
          '[data-testid*="Citation"]',
          '[data-testid="feedback-button-testid"]',
          '[data-testid="message-footer"]',
          '[data-testid="message-toolbar"]',
          '[class*="Citation"]',
          '[class*="citation"]',
          '[class*="Source"]',
          '[class*="source"]',
          '[class*="Footnote"]',
          '[class*="footnote"]',
          '[class*="Feedback"]',
          '[class*="feedback"]',
          '[class*="Toolbar"]',
          '[class*="toolbar"]',
        ].join(", "));
      } catch (_) {
        return false;
      }
    }
    function hasStructuredContent(text) {
      const s = String(text || "");
      return /\\\`\\\`\\\`/.test(s) || /^\\s*(?:[-*]|\\d+\\.)\\s+/m.test(s) || /^\\s*\\|.+\\|\\s*$/m.test(s);
    }
    function shouldPreferFullTurn(replyText, turnText) {
      const reply = nodeText({ innerText: replyText, textContent: replyText });
      const turn = nodeText({ innerText: turnText, textContent: turnText });
      if (!turn) return false;
      if (!reply) return true;
      const delta = turn.length - reply.length;
      if (delta < 20) return false;
      if (hasStructuredContent(turn) && !hasStructuredContent(reply)) return true;
      return delta >= Math.max(60, Math.floor(reply.length * 0.45));
    }
    function assistantRootScore(el) {
      if (!el || !el.getAttribute) return 0;
      let score = 0;
      const role =
        (el.getAttribute("data-message-author-role") ||
          el.getAttribute("data-conversation-role") ||
          el.getAttribute("data-participant") ||
          "").toLowerCase();
      const testid = (el.getAttribute("data-testid") || "").toLowerCase();
      const cls = String(el.className || "").toLowerCase();
      const tag = (el.tagName || "").toLowerCase();
      if (role === "assistant") score += 8;
      if (tag === "cib-message" && (el.getAttribute("type") || "").toLowerCase() === "response") score += 8;
      if (tag === "cib-turn" && (el.getAttribute("type") || "").toLowerCase() === "response") score += 8;
      if (/assistant|bot|copilot/.test(testid)) score += 5;
      if (/reply|message|turn|chat/.test(testid)) score += 2;
      if (/assistant|bot|copilot/.test(cls)) score += 4;
      if (/message|turn|chat/.test(cls)) score += 1;
      if (tag === "article") score += 1;
      return score;
    }
    function sortedVisibleAssistantRoots(doc) {
      const byRole = [...new Set([
        ...queryDeepAll('[data-message-author-role="assistant"]', doc),
        ...queryDeepAll('[data-conversation-role="assistant"]', doc),
        ...queryDeepAll('[data-participant="assistant"]', doc),
        ...queryDeepAll('article[data-message-author-role="assistant"]', doc),
        ...queryDeepAll('cib-message[type="response"]', doc),
        ...queryDeepAll('cib-turn[type="response"]', doc),
      ])];
      const roots = [];
      for (const el of byRole) {
        if (!visible(el) || inComposer(el) || inUserTurn(el)) continue;
        const inner = byRole.some((other) => other !== el && other.contains(el));
        if (inner) continue;
        roots.push(el);
      }
      roots.sort((a, b) => {
        const p = a.compareDocumentPosition(b);
        if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
        if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
        return 0;
      });
      return roots;
    }
    function findAssistantTurnRoot(el) {
      if (!el) return null;
      const replyLen = nodeText(el).length;
      const maxLen = Math.max(1200, replyLen * 12, replyLen + 16000);
      let best = el;
      let bestScore = assistantRootScore(el);
      let bestLen = replyLen;
      let cur = el;
      let depth = 0;
      while (cur && cur.parentElement && depth < 12) {
        cur = cur.parentElement;
        depth++;
        if (!visible(cur) || inComposer(cur) || inUserTurn(cur)) continue;
        const t = nodeText(cur);
        if (!t || t.length > maxLen) continue;
        if (hasSuggestionSurfaceOutsideReply(cur, el)) continue;
        const score = assistantRootScore(cur);
        if (score > bestScore || (score === bestScore && t.length > bestLen)) {
          best = cur;
          bestScore = score;
          bestLen = t.length;
        }
      }
      return best;
    }
    function dedupeStructuredBlocks(blocks) {
      const out = [];
      for (const raw of blocks) {
        const text = nodeText({ innerText: raw, textContent: raw });
        if (!text) continue;
        if (out.at(-1) === text) continue;
        if (out.some((existing) => existing === text)) continue;
        if (out.some((existing) => existing.length > text.length + 80 && existing.includes(text))) continue;
        out.push(text);
      }
      return out;
    }
    function appendStructuredBlock(blocks, raw) {
      const text = nodeText({ innerText: raw, textContent: raw });
      if (!text) return;
      blocks.push(text);
    }
    function extractScriptorCodeText(root) {
      const editors = queryDeepAll(
        '.scriptor-pageContainer[role="document"], [role="document"][aria-label*="Code editor"], .scriptor-code-editor',
        root,
      ).filter((el) => visible(el) && !inComposer(el) && !inUserTurn(el) && !isNoisyReplyNode(el));
      if (!editors.length) return { el: null, text: "" };
      const editor = editors[editors.length - 1];
      const paragraphs = queryDeepAll('.scriptor-paragraph', editor);
      if (!paragraphs.length) {
        return { el: editor, text: nodeText(editor) };
      }
      const lines = paragraphs.map((para) => {
        const runs = Array.from(para.querySelectorAll('.scriptor-textRun'));
        if (runs.length) {
          return runs.map((run) => run.textContent || "").join("").replace(/\u00a0/g, " ");
        }
        return (para.textContent || "").replace(/\u00a0/g, " ");
      });
      return {
        el: editor,
        text: lines.join("\\n").trim(),
      };
    }
    function selectPrimaryMarkdown(root) {
      const candidates = queryDeepAll('[data-testid="markdown-reply"], div[data-message-type="Chat"]', root)
        .filter((el) => visible(el) && !inComposer(el) && !inUserTurn(el) && !isNoisyReplyNode(el));
      if (!candidates.length) return null;
      candidates.sort((a, b) => nodeText(a).length - nodeText(b).length);
      return candidates[candidates.length - 1];
    }
    function findCodePreviewSegment(markdown) {
      if (!markdown) return { container: null, segment: null };
      const preview =
        queryDeepAll('[role="group"][aria-label="Code Preview"]', markdown).find((el) => visible(el)) ||
        queryDeepAll(
          '.scriptor-pageContainer[role="document"], [role="document"][aria-label*="Code editor"], .scriptor-code-editor',
          markdown,
        ).find((el) => visible(el));
      if (!preview) return { container: null, segment: null };
      let segment = preview;
      while (segment.parentElement && segment.parentElement !== markdown) {
        const parent = segment.parentElement;
        if (parent.children && parent.children.length > 1) {
          return { container: parent, segment };
        }
        segment = parent;
      }
      return { container: markdown, segment };
    }
    function extractOrderedMarkdownBlocks(markdown, scriptorCodeText) {
      if (!markdown) return [];
      const { container, segment } = findCodePreviewSegment(markdown);
      if (!container || !segment) {
        const fallback = proseNodeTextWithoutCodePreview(markdown);
        return fallback ? [fallback, scriptorCodeText].filter(Boolean) : [scriptorCodeText].filter(Boolean);
      }
      const blocks = [];
      const children = Array.from(container.children || []);
      let insertedCode = false;
      for (const child of children) {
        if (!child || !visible(child) || inComposer(child) || inUserTurn(child) || isNoisyReplyNode(child)) {
          continue;
        }
        if (child === segment || child.contains(segment)) {
          if (scriptorCodeText) {
            appendStructuredBlock(blocks, scriptorCodeText);
            insertedCode = true;
          }
          continue;
        }
        appendStructuredBlock(blocks, nodeText(child));
      }
      if (!insertedCode && scriptorCodeText) appendStructuredBlock(blocks, scriptorCodeText);
      return dedupeStructuredBlocks(blocks);
    }
    function extractStructuredM365Reply(root) {
      if (!root) return "";
      const scriptorCode = extractScriptorCodeText(root);
      const primaryMarkdown = selectPrimaryMarkdown(root);
      const orderedBlocks = extractOrderedMarkdownBlocks(primaryMarkdown, scriptorCode.text);
      const joined = orderedBlocks.join("\\n\\n");
      if (joined) return joined;
      return nodeText(root);
    }
    function walkElements(root, visit) {
      if (!root) return;
      if (root.nodeType === 1) visit(root);
      const tree = root.nodeType === 9 ? root.documentElement : root;
      if (!tree) return;
      const kids = tree.children || [];
      for (let i = 0; i < kids.length; i++) walkElements(kids[i], visit);
      if (tree.shadowRoot) walkElements(tree.shadowRoot, visit);
    }
    function queryDeepAll(selector, doc) {
      const top = doc?.nodeType === 9 ? (doc.documentElement || doc.body) : doc;
      if (!top) return [];
      const out = [];
      walkElements(top, (el) => {
        try {
          if (el.matches && el.matches(selector)) out.push(el);
        } catch (_) {}
      });
      return out;
    }
    function extractFromDoc(doc) {
      const roots = sortedVisibleAssistantRoots(doc);
      if (roots.length) {
        const lastTurn = roots[roots.length - 1];
        const t = extractStructuredM365Reply(lastTurn);
        if (t.length > 0) return t;
      }
      const m365Replies = queryDeepAll('[data-testid="copilot-message-reply-div"]', doc).filter(
        (el) => visible(el) && !inComposer(el) && !inUserTurn(el),
      );
      if (m365Replies.length) {
        m365Replies.sort((a, b) => {
          const p = a.compareDocumentPosition(b);
          if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
          if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
          return 0;
        });
        const lastM365 = m365Replies[m365Replies.length - 1];
        const replyText = extractStructuredM365Reply(lastM365);
        const turnRoot = findAssistantTurnRoot(lastM365);
        const turnText = turnRoot ? extractStructuredM365Reply(turnRoot) : "";
        if (shouldPreferFullTurn(replyText, turnText)) {
          return turnText;
        }
        if (replyText.length > 0) return replyText;
        if (turnText.length > 0) return turnText;
      }

      const selectors = ${JSON.stringify(ASSISTANT_REPLY_DOM_SELECTORS)};
      const dedup = new Set();
      const els = [];
      for (const s of selectors) {
        for (const el of queryDeepAll(s, doc)) {
          if (!el || dedup.has(el)) continue;
          dedup.add(el);
          if (!visible(el) || inComposer(el) || inUserTurn(el)) continue;
          const t = nodeText(el);
          if (!t) continue;
          els.push(el);
        }
      }
      if (!els.length) return "";
      els.sort((a, b) => {
        const p = a.compareDocumentPosition(b);
        if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
        if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
        return 0;
      });
      const tail = els.slice(-8);
      let best = "";
      for (const el of tail) {
        const t = nodeText(el);
        if (t.length > best.length) best = t;
      }
      return best;
    }
    function bestAcrossIframes(doc, depth) {
      let best = extractFromDoc(doc);
      if (depth > 8) return best;
      let frames;
      try {
        frames = doc.querySelectorAll("iframe");
      } catch (_) {
        return best;
      }
      for (const f of frames) {
        try {
          const c = f.contentDocument;
          if (c) {
            const inner = bestAcrossIframes(c, depth + 1);
            if (inner.length > best.length) best = inner;
          }
        } catch (_) {}
      }
      return best;
    }
    return bestAcrossIframes(document, 0);
  })()`;
}
/**
 * Single Runtime.evaluate for the hot wait loop: avoids doubling CDP latency vs separate
 * isCopilotGenerating + extractAssistantReplyText (Playwright-tuned M365 path uses the same extract).
 */
function copilotDomPollGeneratingAndReplyExpression() {
  return `(() => {
    function visible(el) {
      return el && el.offsetParent !== null;
    }
    function inComposer(el) {
      return !!(el && el.closest(${JSON.stringify(COMPOSER_ANCESTOR_CLOSEST)}));
    }
    function inUserTurn(el) {
      if (!el) return false;
      try {
        if (el.closest('[data-message-author-role="user"]')) return true;
        if (el.closest('[data-message-author-role="User"]')) return true;
        if (el.closest('[data-testid="userMessage"]')) return true;
        if (el.closest('[data-testid*="user-message"]')) return true;
        if (el.closest('[data-testid*="UserMessage"]')) return true;
        if (el.matches && el.matches('cib-message[type="user"]')) return true;
        if (el.closest('[aria-label*="Your message"]')) return true;
        if (el.closest('[aria-label*="your message"]')) return true;
        if (el.closest('[aria-label*="送信した"]')) return true;
        if (el.closest('[aria-label*="自分のメッセージ"]')) return true;
        if (el.closest('[class*="fai-UserMessage"]')) return true;
        if (el.closest('[data-testid="chatQuestion"]')) return true;
      } catch (_) {}
      return false;
    }
    function walkElements(root, visit) {
      if (!root) return;
      if (root.nodeType === 1) visit(root);
      const tree = root.nodeType === 9 ? root.documentElement : root;
      if (!tree) return;
      const kids = tree.children || [];
      for (let i = 0; i < kids.length; i++) walkElements(kids[i], visit);
      if (tree.shadowRoot) walkElements(tree.shadowRoot, visit);
    }
    function queryDeepAll(selector, root) {
      const top = root?.nodeType === 9 ? (root.documentElement || root.body) : root;
      if (!top) return [];
      const out = [];
      walkElements(top, (el) => {
        try {
          if (el.matches && el.matches(selector)) out.push(el);
        } catch (_) {}
      });
      return out;
    }
    function nodeText(el) {
      return (el && (el.innerText || el.textContent) ? (el.innerText || el.textContent) : "").trim();
    }
    function matchesShowMoreControl(el) {
      const text = [
        nodeText(el),
        el?.getAttribute?.("aria-label") || "",
        el?.getAttribute?.("title") || "",
      ].join(" ").toLowerCase();
      return /show more lines|show more|もっと表示/.test(text);
    }
    function lastAssistantTurn(doc) {
      const roots = queryDeepAll('[data-testid="copilot-message-reply-div"]', doc).filter(
        (el) => visible(el) && !inComposer(el) && !inUserTurn(el),
      );
      if (!roots.length) return null;
      roots.sort((a, b) => {
        const p = a.compareDocumentPosition(b);
        if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
        if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
        return 0;
      });
      return roots[roots.length - 1];
    }
    function assistantTurnState(root) {
      if (!root) {
        return { progressOnly: false, hasVisibleAssistantChat: false, hasExpandableCodeBlock: false, structuredReply: "" };
      }
      const progressEls = queryDeepAll(
        '[data-message-type="Progress"], [data-testid="loading-message"], [role="progressbar"], .scc-ChainOfThought',
        root,
      ).filter((el) => visible(el));
      const chatEls = queryDeepAll(
        '[data-testid="markdown-reply"][data-message-type="Chat"], div[data-message-type="Chat"], pre, code',
        root,
      ).filter((el) => visible(el));
      const hasVisibleAssistantChat = chatEls.some((el) => nodeText(el).trim().length > 0);
      const hasExpandableCodeBlock = queryDeepAll('button, [role="button"]', root).some(
        (el) => visible(el) && matchesShowMoreControl(el),
      );
      const structuredReply = (() => {
        try {
          return ${copilotDomReplyExtractIifeExpression()};
        } catch (_) {
          return "";
        }
      })();
      return {
        progressOnly: progressEls.length > 0 && !hasVisibleAssistantChat,
        hasVisibleAssistantChat,
        hasExpandableCodeBlock,
        structuredReply,
      };
    }
    const generating = ${copilotDomGeneratingIifeExpression()};
    const turnState = assistantTurnState(lastAssistantTurn(document));
    const replyRaw = turnState.structuredReply || ${copilotDomReplyExtractIifeExpression()};
    return { generating, reply: replyRaw, ...turnState };
  })()`;
}

export {
  copilotDomGeneratingIifeExpression,
  copilotDomReplyExtractIifeExpression,
  copilotDomPollGeneratingAndReplyExpression,
  assistantTextHasStructuredContent,
  shouldPreferExpandedAssistantTurn,
  stripM365CopilotReplyChrome,
  normalizeStreamingLine,
  lineMatchesStreamingPlaceholder,
  replyEndsWithStreamingPlaceholder,
  stripStreamingPlaceholderTail,
};
