/**
 * Shared DOM IIFEs + strips for M365 Copilot (generated by build-copilot-dom-modules.mjs).
 */
export const COMPOSER_ANCESTOR_CLOSEST =
  '#m365-chat-editor-target-element, [data-lexical-editor="true"], [role="textbox"][aria-label*="メッセージを送信"], [role="textbox"][aria-label*="Send a message"], [role="textbox"][aria-label*="Message"], [role="textbox"][aria-label*="message"], [role="textbox"][aria-label*="Copilot"]';

export const STREAMING_STOP_SELECTORS = [
  ".fai-SendButton__stopBackground",
  'button[aria-label*="生成を停止"]',
  'button[aria-label*="Stop generating"]',
  'button[aria-label*="Stop response"]',
  'button[aria-label*="停止"]',
  'button[data-testid="stopGeneratingButton"]',
  'button[data-testid*="stop"]',
  '[data-testid*="StopGenerating"]',
  '[class*="StopGenerating"]',
  '[class*="stopGenerating"]'
];

export const ASSISTANT_REPLY_DOM_SELECTORS = [
  /** M365 Copilot web (Fluent): narrow reply body; prefer over generic article/markdown hits. */
  '[data-testid="copilot-message-reply-div"]',
  '[class*="fai-CopilotMessage"]',
  '[data-testid="markdown-reply"]',
  '[data-testid*="message-content"]',
  '[data-testid*="message-body"]',
  '[data-testid*="assistant"]',
  '[data-message-author-role="assistant"]',
  'article[data-message-author-role="assistant"]',
  'div[data-message-type="Chat"]',
  '[role="article"]',
  ".markdown-body",
  ".fui-ChatMessageBody",
  '[class*="ChatMessage"]',
  '[class*="MessageBody"]',
  '[class*="message-body"]',
  "cib-message[type='response']",
  "cib-message .content",
  "cib-serp",
  "cib-rich-card"
];

/** Strip M365 Copilot Web UI a11y chrome from innerText ("Copilot said:", branding line). */
function stripM365CopilotReplyChrome(text) {
  let s = String(text || "").trim();
  if (!s) return s;
  s = s.replace(/^Copilot said:\s*/i, "");
  s = s.replace(/^Copilot\s*(\n+|$)/im, "");
  return s.trim();
}

/** Last-line / tail matches while Copilot is still streaming (Stop button may not be visible yet). */
export const COPILOT_STREAMING_PLACEHOLDER_LAST_LINES = [
  "応答を生成しています",
  "応答を作成しています",
  "生成しています",
  "作成しています",
  "考えています",
  "処理しています",
  "しばらくお待ちください",
  "Generating response",
  "Creating response",
  "Please wait",
];

function normalizeStreamingLine(line) {
  return String(line || "")
    .replace(/\u2026/g, "...")
    .replace(/\u00a0/g, " ")
    .trim();
}

function lineMatchesStreamingPlaceholder(line) {
  const n = normalizeStreamingLine(line).toLowerCase();
  if (!n) return false;
  for (const p of COPILOT_STREAMING_PLACEHOLDER_LAST_LINES) {
    if (n === p.toLowerCase()) return true;
  }
  if (/^thinking[.\u2026…\s]*$/i.test(n)) return true;
  if (/^generating[.\u2026…\s]*$/i.test(n)) return true;
  return false;
}

function replyEndsWithStreamingPlaceholder(text) {
  const s = String(text || "").trimEnd();
  if (!s) return false;
  const parts = s.split(/\r?\n/);
  for (let i = parts.length - 1; i >= 0; i--) {
    const t = parts[i].trim();
    if (!t) continue;
    return lineMatchesStreamingPlaceholder(t);
  }
  return false;
}

/** Remove trailing placeholder lines Copilot appends to innerText during streaming. */
function stripStreamingPlaceholderTail(text) {
  let s = String(text || "");
  for (let guard = 0; guard < 48; guard++) {
    const lines = s.split(/\r?\n/);
    let lastIdx = lines.length - 1;
    while (lastIdx >= 0 && !lines[lastIdx].trim()) lastIdx--;
    if (lastIdx < 0) break;
    if (!lineMatchesStreamingPlaceholder(lines[lastIdx])) break;
    lines.splice(lastIdx, 1);
    s = lines.join("\n");
  }
  return s.trim();
}

export const RESPONSE_TIMEOUT_MS = 18e4;
/** Main loop sleep in waitForDomResponse (was 1000ms → ~3min wall time on phantom “generating”). */
export const RESPONSE_POLL_INTERVAL_MS = 500;
/** Consecutive polls with raw generating=true before treating “stop” UI as phantom (was 55 @ 1s ≈ 55s lost). */
export const RESPONSE_PHANTOM_GENERATING_POLLS = 22;
/** After DOM looks stable, pause before re-extract (was 2800ms). */
export const RESPONSE_POST_STABLE_MS = 1000;

export const CHATHUB_ASSISTANT_MIN_CHARS = 2;

function copilotDomGeneratingIifeExpression() {
  return `(() => {
    function reallyVisible(el) {
      if (!el || el.offsetParent === null) return false;
      const st = getComputedStyle(el);
      if (st.visibility === "hidden" || st.display === "none" || Number(st.opacity) === 0) return false;
      const r = el.getBoundingClientRect();
      if (r.width < 3 || r.height < 3) return false;
      return r.bottom > 2 && r.right > 2 && r.top < innerHeight - 2 && r.left < innerWidth - 2;
    }
    function walkElements(root, visit) {
      if (!root) return;
      if (root.nodeType === 1) visit(root);
      const tree = root.nodeType === 9 ? root.documentElement : root;
      if (!tree) return;
      const kids = tree.children || [];
      for (let i = 0; i < kids.length; i++) walkElements(kids[i], visit);
      if (tree.shadowRoot) walkElements(tree.shadowRoot, visit);
    }
    function queryDeepAll(selector, doc) {
      const top = doc.documentElement || doc.body;
      if (!top) return [];
      const out = [];
      walkElements(top, (el) => {
        try {
          if (el.matches && el.matches(selector)) out.push(el);
        } catch (_) {}
      });
      return out;
    }
    function isGeneratingInDoc(doc) {
      const sels = ${JSON.stringify(STREAMING_STOP_SELECTORS)};
      for (const s of sels) {
        for (const el of queryDeepAll(s, doc)) {
          if (reallyVisible(el)) return true;
        }
      }
      for (const b of queryDeepAll("button, [role='button'], [role='menuitem']", doc)) {
        if (!reallyVisible(b)) continue;
        const a = (b.getAttribute("aria-label") || b.getAttribute("title") || "").toLowerCase();
        if (!a) continue;
        if (/\\bstop\\b/.test(a) && /generat|stream|response|応答|生成|回答|作成/.test(a)) return true;
        if (/\\bcancel\\b/.test(a) && /response|応答|生成|回答|stream/.test(a)) return true;
        if (
          /arrêt|arret|interromp|interrupt|detener|detén|abbrechen/.test(a) &&
          /génér|genér|generat|réponse|response|respuesta|stream|flux|応答|生成/.test(a)
        )
          return true;
      }
      return false;
    }
    function scanDocs(doc, depth) {
      if (isGeneratingInDoc(doc)) return true;
      if (depth > 8) return false;
      let frames;
      try {
        frames = doc.querySelectorAll("iframe");
      } catch (_) {
        return false;
      }
      for (const f of frames) {
        try {
          const c = f.contentDocument;
          if (c && scanDocs(c, depth + 1)) return true;
        } catch (_) {}
      }
      return false;
    }
    return scanDocs(document, 0);
  })()`;
}

async function isCopilotGenerating(session) {
  const r = await session.evaluate(copilotDomGeneratingIifeExpression()).catch(() => ({ value: false }));
  return r?.value === true;
}

/**
 * Prefer the outermost last assistant *turn*. Walks open shadow roots and same-origin iframes
 * (M365 often hosts the transcript in an embedded frame).
 */
function copilotDomReplyExtractIifeExpression() {
  return `(() => {
    function visible(el) {
      return el && el.offsetParent !== null;
    }
    function inComposer(el) {
      return !!(el && el.closest(${JSON.stringify(COMPOSER_ANCESTOR_CLOSEST)}));
    }
    /** User bubbles often match generic markdown/article selectors — never treat as assistant reply. */
    function inUserTurn(el) {
      if (!el) return false;
      try {
        if (el.closest('[data-message-author-role="user"]')) return true;
        if (el.closest('[data-message-author-role="User"]')) return true;
        if (el.closest('[data-testid="userMessage"]')) return true;
        if (el.closest('[data-testid*="user-message"]')) return true;
        if (el.closest('[data-testid*="UserMessage"]')) return true;
        if (el.matches && el.matches('cib-message[type="user"]')) return true;
        if (el.closest('[aria-label*="Your message"]')) return true;
        if (el.closest('[aria-label*="your message"]')) return true;
        if (el.closest('[aria-label*="送信した"]')) return true;
        if (el.closest('[aria-label*="自分のメッセージ"]')) return true;
        if (el.closest('[class*="fai-UserMessage"]')) return true;
        if (el.closest('[data-testid="chatQuestion"]')) return true;
      } catch (_) {}
      return false;
    }
    function nodeText(el) {
      const t = (el.innerText || el.textContent || "").trim();
      return t;
    }
    function walkElements(root, visit) {
      if (!root) return;
      if (root.nodeType === 1) visit(root);
      const tree = root.nodeType === 9 ? root.documentElement : root;
      if (!tree) return;
      const kids = tree.children || [];
      for (let i = 0; i < kids.length; i++) walkElements(kids[i], visit);
      if (tree.shadowRoot) walkElements(tree.shadowRoot, visit);
    }
    function queryDeepAll(selector, doc) {
      const top = doc.documentElement || doc.body;
      if (!top) return [];
      const out = [];
      walkElements(top, (el) => {
        try {
          if (el.matches && el.matches(selector)) out.push(el);
        } catch (_) {}
      });
      return out;
    }
    function extractFromDoc(doc) {
      const m365Replies = queryDeepAll('[data-testid="copilot-message-reply-div"]', doc).filter(
        (el) => visible(el) && !inComposer(el) && !inUserTurn(el),
      );
      if (m365Replies.length) {
        m365Replies.sort((a, b) => {
          const p = a.compareDocumentPosition(b);
          if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
          if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
          return 0;
        });
        const lastM365 = m365Replies[m365Replies.length - 1];
        const tm = nodeText(lastM365);
        if (tm.length > 0) return tm;
      }
      const byRole = [...new Set([
        ...queryDeepAll('[data-message-author-role="assistant"]', doc),
        ...queryDeepAll('article[data-message-author-role="assistant"]', doc)
      ])];
      const roots = [];
      for (const el of byRole) {
        if (!visible(el) || inComposer(el) || inUserTurn(el)) continue;
        const inner = byRole.some((other) => other !== el && other.contains(el));
        if (inner) continue;
        roots.push(el);
      }
      roots.sort((a, b) => {
        const p = a.compareDocumentPosition(b);
        if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
        if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
        return 0;
      });
      if (roots.length) {
        const lastTurn = roots[roots.length - 1];
        const t = nodeText(lastTurn);
        if (t.length > 0) return t;
      }

      const selectors = ${JSON.stringify(ASSISTANT_REPLY_DOM_SELECTORS)};
      const dedup = new Set();
      const els = [];
      for (const s of selectors) {
        for (const el of queryDeepAll(s, doc)) {
          if (!el || dedup.has(el)) continue;
          dedup.add(el);
          if (!visible(el) || inComposer(el) || inUserTurn(el)) continue;
          const t = nodeText(el);
          if (!t) continue;
          els.push(el);
        }
      }
      if (!els.length) return "";
      els.sort((a, b) => {
        const p = a.compareDocumentPosition(b);
        if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
        if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
        return 0;
      });
      const tail = els.slice(-8);
      let best = "";
      for (const el of tail) {
        const t = nodeText(el);
        if (t.length > best.length) best = t;
      }
      return best;
    }
    function bestAcrossIframes(doc, depth) {
      let best = extractFromDoc(doc);
      if (depth > 8) return best;
      let frames;
      try {
        frames = doc.querySelectorAll("iframe");
      } catch (_) {
        return best;
      }
      for (const f of frames) {
        try {
          const c = f.contentDocument;
          if (c) {
            const inner = bestAcrossIframes(c, depth + 1);
            if (inner.length > best.length) best = inner;
          }
        } catch (_) {}
      }
      return best;
    }
    return bestAcrossIframes(document, 0);
  })()`;
}
/**
 * Single Runtime.evaluate for the hot wait loop: avoids doubling CDP latency vs separate
 * isCopilotGenerating + extractAssistantReplyText (Playwright-tuned M365 path uses the same extract).
 */
function copilotDomPollGeneratingAndReplyExpression() {
  return `(() => {
    const generating = ${copilotDomGeneratingIifeExpression()};
    const replyRaw = ${copilotDomReplyExtractIifeExpression()};
    return { generating, reply: replyRaw };
  })()`;
}

export {
  copilotDomGeneratingIifeExpression,
  copilotDomReplyExtractIifeExpression,
  copilotDomPollGeneratingAndReplyExpression,
  stripM365CopilotReplyChrome,
  normalizeStreamingLine,
  lineMatchesStreamingPlaceholder,
  replyEndsWithStreamingPlaceholder,
  stripStreamingPlaceholderTail,
};

