/**
 * waitForDomResponse — same logic as copilot_server.js (generated by build-copilot-dom-modules.mjs).
 */
import {
  COMPOSER_ANCESTOR_CLOSEST,
  copilotDomPollGeneratingAndReplyExpression,
  copilotDomReplyExtractIifeExpression,
  stripM365CopilotReplyChrome,
  stripStreamingPlaceholderTail,
  replyEndsWithStreamingPlaceholder,
  CHATHUB_ASSISTANT_MIN_CHARS,
  RESPONSE_POLL_INTERVAL_MS,
  RESPONSE_TIMEOUT_MS,
  RESPONSE_PHANTOM_GENERATING_POLLS,
  RESPONSE_POST_STABLE_MS,
} from "./copilot_dom_poll.mjs";

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

async function pollCopilotGeneratingAndReply(session) {
  const r = await session
    .evaluate(copilotDomPollGeneratingAndReplyExpression())
    .catch(() => ({ value: { generating: false, reply: "" } }));
  const v = r?.value;
  const gen = v?.generating === true;
  const reply = stripM365CopilotReplyChrome(typeof v?.reply === "string" ? v.reply : "");
  return { generating: gen, reply };
}

async function extractAssistantReplyText(session) {
  const r = await session.evaluate(copilotDomReplyExtractIifeExpression()).catch(() => ({ value: "" }));
  return stripStreamingPlaceholderTail(
    stripM365CopilotReplyChrome(typeof r?.value === "string" ? r.value : ""),
  );
}

async function extractAssistantReplyStrict(session) {
  const r = await session.evaluate(`(() => {
    function visible(el) {
      return el && el.offsetParent !== null;
    }
    function inComposer(el) {
      return !!(el && el.closest(${JSON.stringify(COMPOSER_ANCESTOR_CLOSEST)}));
    }
    function inUserTurn(el) {
      if (!el) return false;
      try {
        if (el.closest('[data-message-author-role="user"]')) return true;
        if (el.closest('[data-message-author-role="User"]')) return true;
        if (el.closest('[data-testid="userMessage"]')) return true;
        if (el.closest('[data-testid*="user-message"]')) return true;
        if (el.closest('[data-testid*="UserMessage"]')) return true;
        if (el.matches && el.matches('cib-message[type="user"]')) return true;
        if (el.closest('[aria-label*="Your message"]')) return true;
        if (el.closest('[aria-label*="your message"]')) return true;
        if (el.closest('[aria-label*="送信した"]')) return true;
        if (el.closest('[aria-label*="自分のメッセージ"]')) return true;
        if (el.closest('[class*="fai-UserMessage"]')) return true;
        if (el.closest('[data-testid="chatQuestion"]')) return true;
      } catch (_) {}
      return false;
    }
    function walkElements(root, visit) {
      if (!root) return;
      if (root.nodeType === 1) visit(root);
      const tree = root.nodeType === 9 ? root.documentElement : root;
      if (!tree) return;
      const kids = tree.children || [];
      for (let i = 0; i < kids.length; i++) walkElements(kids[i], visit);
      if (tree.shadowRoot) walkElements(tree.shadowRoot, visit);
    }
    function queryDeepAll(selector, doc) {
      const top = doc.documentElement || doc.body;
      if (!top) return [];
      const out = [];
      walkElements(top, (el) => {
        try {
          if (el.matches && el.matches(selector)) out.push(el);
        } catch (_) {}
      });
      return out;
    }
    function extractFromDoc(doc) {
      const m365Replies = queryDeepAll('[data-testid="copilot-message-reply-div"]', doc).filter(
        (el) => visible(el) && !inComposer(el) && !inUserTurn(el),
      );
      if (m365Replies.length) {
        m365Replies.sort((a, b) => {
          const p = a.compareDocumentPosition(b);
          if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
          if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
          return 0;
        });
        const lastM365 = m365Replies[m365Replies.length - 1];
        const tm = (lastM365.innerText || lastM365.textContent || "").trim();
        if (tm.length > 0) return tm;
      }
      const byRole = [
        ...queryDeepAll('[data-message-author-role="assistant"]', doc),
        ...queryDeepAll('article[data-message-author-role="assistant"]', doc),
      ];
      const roots = [];
      for (const el of byRole) {
        if (!visible(el) || inComposer(el) || inUserTurn(el)) continue;
        const inner = byRole.some((other) => other !== el && other.contains(el));
        if (inner) continue;
        roots.push(el);
      }
      roots.sort((a, b) => {
        const p = a.compareDocumentPosition(b);
        if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
        if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
        return 0;
      });
      if (!roots.length) return "";
      const lastTurn = roots[roots.length - 1];
      return (lastTurn.innerText || lastTurn.textContent || "").trim();
    }
    function bestAcrossIframes(doc, depth) {
      let best = extractFromDoc(doc);
      if (depth > 8) return best;
      let frames;
      try {
        frames = doc.querySelectorAll("iframe");
      } catch (_) {
        return best;
      }
      for (const f of frames) {
        try {
          const c = f.contentDocument;
          if (c) {
            const inner = bestAcrossIframes(c, depth + 1);
            if (inner.length > best.length) best = inner;
          }
        } catch (_) {}
      }
      return best;
    }
    return bestAcrossIframes(document, 0);
  })()`).catch(() => ({ value: "" }));
  return stripM365CopilotReplyChrome(typeof r?.value === "string" ? r.value : "");
}

async function extractAssistantReplyHeuristic(session) {
  const r = await session.evaluate(`(() => {
    function visible(el) {
      return el && el.offsetParent !== null;
    }
    function inComposer(el) {
      return !!(el && el.closest(${JSON.stringify(COMPOSER_ANCESTOR_CLOSEST)}));
    }
    function inUserTurn(el) {
      if (!el) return false;
      try {
        if (el.closest('[data-message-author-role="user"]')) return true;
        if (el.closest('[data-message-author-role="User"]')) return true;
        if (el.closest('[data-testid="userMessage"]')) return true;
        if (el.closest('[data-testid*="user-message"]')) return true;
        if (el.closest('[data-testid*="UserMessage"]')) return true;
        if (el.matches && el.matches('cib-message[type="user"]')) return true;
        if (el.closest('[aria-label*="Your message"]')) return true;
        if (el.closest('[aria-label*="your message"]')) return true;
        if (el.closest('[aria-label*="送信した"]')) return true;
        if (el.closest('[aria-label*="自分のメッセージ"]')) return true;
        if (el.closest('[class*="fai-UserMessage"]')) return true;
        if (el.closest('[data-testid="chatQuestion"]')) return true;
      } catch (_) {}
      return false;
    }
    function nodeText(el) {
      return (el.innerText || el.textContent || "").trim();
    }
    function walkElements(root, visit) {
      if (!root) return;
      if (root.nodeType === 1) visit(root);
      const tree = root.nodeType === 9 ? root.documentElement : root;
      if (!tree) return;
      const kids = tree.children || [];
      for (let i = 0; i < kids.length; i++) walkElements(kids[i], visit);
      if (tree.shadowRoot) walkElements(tree.shadowRoot, visit);
    }
    function queryDeepAll(selector, doc) {
      const top = doc.documentElement || doc.body;
      if (!top) return [];
      const out = [];
      walkElements(top, (el) => {
        try {
          if (el.matches && el.matches(selector)) out.push(el);
        } catch (_) {}
      });
      return out;
    }
    const selectors = [
      '[data-testid="copilot-message-reply-div"]',
      '[data-testid*="assistant-message"]',
      '[data-testid*="AssistantMessage"]',
      '[data-testid*="bot-message"]',
      '[data-conversation-role="assistant"]',
      '[data-participant="assistant"]',
      'cib-message[type="response"]',
      'cib-message[conversation="response"]',
      'cib-turn[type="response"]',
      '[class*="assistantMessage"]',
      '[class*="BotMessage"]',
    ];
    function extractFromDoc(doc) {
      const m365Replies = queryDeepAll('[data-testid="copilot-message-reply-div"]', doc).filter(
        (el) => visible(el) && !inComposer(el) && !inUserTurn(el),
      );
      if (m365Replies.length) {
        m365Replies.sort((a, b) => {
          const p = a.compareDocumentPosition(b);
          if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
          if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
          return 0;
        });
        const lastM365 = m365Replies[m365Replies.length - 1];
        const tm = nodeText(lastM365);
        if (tm.length > 0) return tm;
      }
      const dedup = new Set();
      const candidates = [];
      for (const s of selectors) {
        for (const el of queryDeepAll(s, doc)) {
          if (!el || dedup.has(el)) continue;
          dedup.add(el);
          if (!visible(el) || inComposer(el) || inUserTurn(el)) continue;
          const t = nodeText(el);
          if (t.length < 12) continue;
          candidates.push(el);
        }
      }
      if (!candidates.length) return "";
      candidates.sort((a, b) => {
        const p = a.compareDocumentPosition(b);
        if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
        if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
        return 0;
      });
      const last = candidates[candidates.length - 1];
      return nodeText(last);
    }
    function bestAcrossIframes(doc, depth) {
      let best = extractFromDoc(doc);
      if (depth > 8) return best;
      let frames;
      try {
        frames = doc.querySelectorAll("iframe");
      } catch (_) {
        return best;
      }
      for (const f of frames) {
        try {
          const c = f.contentDocument;
          if (c) {
            const inner = bestAcrossIframes(c, depth + 1);
            if (inner.length > best.length) best = inner;
          }
        } catch (_) {}
      }
      return best;
    }
    return bestAcrossIframes(document, 0);
  })()`).catch(() => ({ value: "" }));
  return stripM365CopilotReplyChrome(typeof r?.value === "string" ? r.value : "");
}

/** Loose DOM extract length ≈ pasted prompt → still showing user wall, not a real assistant reply. */
function domExtractLooksLikeSubmittedPrompt(textLen, submittedLen) {
  if (!submittedLen || submittedLen < 1200) return false;
  const low = submittedLen * 0.72;
  const high = submittedLen * 1.2;
  return textLen >= low && textLen <= high;
}

async function resolveAssistantReplyForReturn(session, looseText, submittedPromptLen, netCapture = null) {
  const loose = stripStreamingPlaceholderTail((looseText || "").trim());
  if (!domExtractLooksLikeSubmittedPrompt(loose.length, submittedPromptLen)) return loose;
  const strict = stripStreamingPlaceholderTail((await extractAssistantReplyStrict(session)).trim());
  if (strict.length >= 20 && strict.length < loose.length * 0.88) {
    console.error(
      "[copilot:response] prefer strict assistant over prompt-length loose extract strictLen=",
      strict.length,
      "looseLen=",
      loose.length,
      "submittedPromptLen=",
      submittedPromptLen,
    );
    return strict;
  }
  const heur = stripStreamingPlaceholderTail((await extractAssistantReplyHeuristic(session)).trim());
  if (heur.length >= 15) {
    if (!domExtractLooksLikeSubmittedPrompt(heur.length, submittedPromptLen)) {
      console.error("[copilot:response] prefer heuristic assistant extract len=", heur.length);
      return heur;
    }
    if (heur.length < submittedPromptLen * 0.38) {
      console.error(
        "[copilot:response] heuristic assistant short vs submitted — accepting len=",
        heur.length,
      );
      return heur;
    }
  }
  if (netCapture) {
    try {
      if (typeof netCapture.pickAssistantFromChathubWs === "function") {
        const chw = stripStreamingPlaceholderTail(netCapture.pickAssistantFromChathubWs().trim());
        if (chw.length >= CHATHUB_ASSISTANT_MIN_CHARS && !networkExtractLooksLikeGarbage(chw)) {
          console.error("[copilot:response] M365 Chathub WebSocket assistant len=", chw.length);
          return chw;
        }
      }
      const shortN = stripStreamingPlaceholderTail(
        (await netCapture.pickBestShortAssistant(loose.length, submittedPromptLen)).trim(),
      );
      if (shortN.length >= 20) {
        console.error("[copilot:response] network short-assistant len=", shortN.length);
        return shortN;
      }
      const nw = stripStreamingPlaceholderTail(
        (await netCapture.pickBestOver("", submittedPromptLen)).trim(),
      );
      if (
        nw.length >= CHATHUB_ASSISTANT_MIN_CHARS &&
        !networkExtractLooksLikeGarbage(nw) &&
        (!domExtractLooksLikeSubmittedPrompt(nw.length, submittedPromptLen) || nw.length < loose.length * 0.88)
      ) {
        console.error("[copilot:response] network pickBestOver(\"\") len=", nw.length);
        return nw;
      }
    } catch (e) {
      console.error("[copilot:response] network extract error:", e?.message || e);
    }
  }
  return null;
}

async function waitForDomResponse(session, netCapture = null, submittedPromptLen = 0, abortCheck = null) {
  const wire = async (s) => {
    let t = stripStreamingPlaceholderTail(String(s ?? "").trim());
    if (netCapture) t = stripStreamingPlaceholderTail(String(await netCapture.pickBestOver(t, submittedPromptLen) ?? "").trim());
    return t;
  };

  await sleep(520);
  let baselineLen = (await pollCopilotGeneratingAndReply(session)).reply.trim().length;
  /** If we captured the user's long prompt as "assistant", minDoneLen becomes unreachable (baseline+2 > len forever). */
  if (baselineLen > 12_000) {
    console.error(
      "[copilot:response] baseline assistant extract is huge (likely user bubble); resetting baseline for completion logic, was",
      baselineLen,
    );
    baselineLen = 0;
  }
  const waitStarted = Date.now();
  const deadline = waitStarted + RESPONSE_TIMEOUT_MS;
  let prev = baselineLen;
  let stable = 0;
  let streamed = false;
  /** When `RELAY_COPILOT_DEBUG_POLL=1`, periodic poll logs start ≥10s after this (avoids immediate spam with lastDiag=0). */
  let lastDiag = waitStarted;
  /** Consecutive polls with generating=false; used to finish sooner when the UI is idle but ticks were high. */
  let quietGen = 0;
  /** Phantom “stop generating” in DOM keeps this true forever — ignore after N seconds. */
  let genStreak = 0;
  /** M365 reply-div yields short answers (e.g. "OK"); keep floor low but still require growth vs baseline. */
  const minDoneLen = () =>
    Math.max(streamed ? 2 : 5, baselineLen + (streamed ? 1 : 5));

  while (Date.now() < deadline) {
    if (abortCheck && abortCheck()) {
      throw new Error("relay_copilot_aborted");
    }
    await sleep(RESPONSE_POLL_INTERVAL_MS);
    const { generating: generatingRaw, reply: replyRaw } = await pollCopilotGeneratingAndReply(session);
    const reply = replyRaw.trim();
    const len = reply.length;

    if (generatingRaw) {
      genStreak++;
    } else {
      genStreak = 0;
    }
    const ignorePhantomStop = genStreak >= RESPONSE_PHANTOM_GENERATING_POLLS;
    const streamingPlaceholderTail = replyEndsWithStreamingPlaceholder(reply);
    const generating =
      streamingPlaceholderTail || (generatingRaw && !ignorePhantomStop);
    if (generating) quietGen = 0;
    else quietGen++;
    if (ignorePhantomStop && genStreak === RESPONSE_PHANTOM_GENERATING_POLLS) {
      console.error(
        "[copilot:response] stop-button heuristic stuck; ignoring phantom generating after",
        RESPONSE_PHANTOM_GENERATING_POLLS,
        "polls (~",
        Math.round(
          (RESPONSE_PHANTOM_GENERATING_POLLS * RESPONSE_POLL_INTERVAL_MS) / 1000,
        ),
        "s)",
      );
    }

    if (process.env.RELAY_COPILOT_DEBUG_POLL === "1" && Date.now() - lastDiag > 10e3) {
      lastDiag = Date.now();
      let bodyLen = 0;
      try {
        const br = await session.evaluate(
          `(() => (document.body && document.body.innerText) ? document.body.innerText.length : 0)()`,
        );
        bodyLen = Number(br.value) || 0;
      } catch {
        /* ignore */
      }
      console.error("[copilot:response] poll", {
        elapsedSec: Math.floor((Date.now() - waitStarted) / 1000),
        timeoutInSec: Math.max(0, Math.floor((deadline - Date.now()) / 1000)),
        len,
        bodyLen,
        generating,
        generatingRaw,
        streamingPlaceholderTail,
        genStreak,
        streamed,
        stable,
        baselineLen,
      });
    }

    if (prev > 400 && len < prev * 0.15 && len < 800) {
      console.error("[copilot:response] baseline reset (new assistant bubble), prev=", prev, "len=", len);
      baselineLen = len;
      streamed = true;
      stable = 0;
      prev = len;
      continue;
    }

    if (len > baselineLen + 18) streamed = true;

    if (generating) {
      streamed = true;
      stable = 0;
      prev = len;
      continue;
    }

    if (len > prev + 5) {
      stable = 0;
      prev = len;
      continue;
    }

    const grewEnough =
      streamed ||
      len >= baselineLen + 10 ||
      len >= 120 ||
      len >= minDoneLen() ||
      (quietGen >= 5 && !generating && len > baselineLen && len >= 1);
    const settled = Math.abs(len - prev) <= 12;
    let needStableTicks = len > 220 ? 2 : 3;
    if (
      !generating &&
      quietGen >= 5 &&
      len >= Math.max(baselineLen + 6, 18) &&
      (streamed || len >= baselineLen + 8)
    ) {
      needStableTicks = Math.min(needStableTicks, 2);
    }
    const lengthOkForDone =
      (len >= minDoneLen() ||
        (quietGen >= 5 && !generating && len > baselineLen && len >= 1)) &&
      !streamingPlaceholderTail;
    if (settled && grewEnough && lengthOkForDone) {
      stable++;
      if (stable >= needStableTicks) {
        const postStableMs = len < 500 ? Math.min(750, RESPONSE_POST_STABLE_MS) : RESPONSE_POST_STABLE_MS;
        await sleep(postStableMs);
        const replyLate = (await pollCopilotGeneratingAndReply(session)).reply.trim();
        if (replyLate.length > len + 40) {
          console.error("[copilot:response] post-stable growth, keep waiting", len, "->", replyLate.length);
          stable = 0;
          prev = len;
          continue;
        }
        const candidate = replyLate.length >= len ? replyLate : reply;
        if (replyEndsWithStreamingPlaceholder(candidate)) {
          console.error("[copilot:response] post-stable reply still ends with streaming placeholder; keep waiting");
          stable = 0;
          prev = len;
          continue;
        }
        const out = await resolveAssistantReplyForReturn(session, candidate, submittedPromptLen, netCapture);
        if (out == null) {
          console.error(
            "[copilot:response] refuse false done: loose extract matches submitted prompt length but no strict assistant yet (submitted=",
            submittedPromptLen,
            "loose=",
            candidate.length,
            ")",
          );
          stable = 0;
          prev = len;
          continue;
        }
        console.error("[copilot:response] done, len=", out.length, "stable=", stable);
        return await wire(out);
      }
    } else {
      stable = 0;
    }

    /** Generation ended long ago but len stayed at a huge false positive — finish and return best strict assistant extract. */
    if (streamed && !generating && quietGen >= 14 && len > 8_000) {
      const strict = await extractAssistantReplyStrict(session);
      if (
        strict.length >= 12 &&
        strict.length < len * 0.85 &&
        (!domExtractLooksLikeSubmittedPrompt(strict.length, submittedPromptLen) || strict.length < len * 0.25)
      ) {
        console.error(
          "[copilot:response] done (quiet + strict assistant shorter than bogus len)",
          "strictLen=",
          strict.length,
          "domLen=",
          len,
        );
        return await wire(strict);
      }
    }

    /** DOM still looks like prompt echo — retry network/heuristic while Copilot has finished streaming. */
    if (
      netCapture &&
      streamed &&
      !generating &&
      domExtractLooksLikeSubmittedPrompt(len, submittedPromptLen) &&
      quietGen >= 4 &&
      quietGen % 4 === 0
    ) {
      const early = await resolveAssistantReplyForReturn(session, reply, submittedPromptLen, netCapture);
      if (early != null) {
        console.error("[copilot:response] done (resolved during echo wait) len=", early.length);
        return await wire(early);
      }
    }

    prev = len;
  }

  const fbLoose = (await extractAssistantReplyText(session)).trim();
  const fbResolved = await resolveAssistantReplyForReturn(session, fbLoose, submittedPromptLen, netCapture);
  if (fbResolved != null) {
    console.error("[copilot:response] timeout, using resolved assistant len=", fbResolved.length);
    return await wire(fbResolved);
  }
  if (fbLoose.length >= 12 && !domExtractLooksLikeSubmittedPrompt(fbLoose.length, submittedPromptLen)) {
    console.error("[copilot:response] timeout, returning partial len=", fbLoose.length);
    return await wire(fbLoose);
  }
  if (fbLoose.length >= 12) {
    console.error(
      "[copilot:response] timeout, skipping prompt-echo loose extract (len=",
      fbLoose.length,
      ") — trying body/network",
    );
  }
  const bodyFb = await session.evaluate(`(() => {
    const raw = (document.body && document.body.innerText) ? document.body.innerText.trim() : "";
    if (raw.length < 80) return "";
    const nl = String.fromCharCode(10);
    const lines = raw.split(nl).map((l) => l.trim()).filter(Boolean);
    const tail = lines.slice(-40).join(nl);
    return tail.length > 200 ? tail.slice(-12e3) : "";
  })()`).catch(() => ({ value: "" }));
  const bodyStr = typeof bodyFb?.value === "string" ? bodyFb.value : "";
  if (bodyStr.length >= 80) {
    console.error("[copilot:response] timeout body tail fallback len=", bodyStr.length);
    return await wire(bodyStr);
  }
  if (netCapture) {
    const sn = (await netCapture.pickBestShortAssistant(fbLoose.length, submittedPromptLen)).trim();
    if (sn.length >= CHATHUB_ASSISTANT_MIN_CHARS) {
      console.error("[copilot:response] DOM empty; using network short-assistant len=", sn.length);
      return await wire(sn);
    }
    const nw = await netCapture.pickBestOver("", submittedPromptLen);
    const nwTrim = nw.trim();
    if (nwTrim.length >= CHATHUB_ASSISTANT_MIN_CHARS && !networkExtractLooksLikeGarbage(nwTrim)) {
      console.error("[copilot:response] DOM empty; using network-only len=", nwTrim.length);
      return await wire(nwTrim);
    }
  }
  throw new Error("Copilot response not found in DOM");
}

export {
  sleep,
  pollCopilotGeneratingAndReply,
  extractAssistantReplyStrict,
  extractAssistantReplyText,
  extractAssistantReplyHeuristic,
  domExtractLooksLikeSubmittedPrompt,
  resolveAssistantReplyForReturn,
  waitForDomResponse,
};
