/**
 * waitForDomResponse — same logic as copilot_server.js (generated by build-copilot-dom-modules.mjs).
 */
import {
  COMPOSER_ANCESTOR_CLOSEST,
  copilotDomPollGeneratingAndReplyExpression,
  copilotDomReplyExtractIifeExpression,
  stripM365CopilotReplyChrome,
  stripStreamingPlaceholderTail,
  replyEndsWithStreamingPlaceholder,
  CHATHUB_ASSISTANT_MIN_CHARS,
  RESPONSE_POLL_INTERVAL_MS,
  RESPONSE_TIMEOUT_MS,
  RESPONSE_PHANTOM_GENERATING_POLLS,
  RESPONSE_POST_STABLE_MS,
} from "./copilot_dom_poll.mjs";

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

function decodeJwtSegmentBase64Url(seg) {
  if (!seg || typeof seg !== "string") return "";
  try {
    const pad = (x) => x + "=".repeat((4 - (x.length % 4)) % 4);
    const b64 = pad(seg.replace(/-/g, "+").replace(/_/g, "/"));
    return Buffer.from(b64, "base64").toString("utf8");
  } catch {
    return "";
  }
}

function stringLooksLikeJwt(text) {
  const t = String(text || "").trim();
  const parts = t.split(".");
  if (parts.length !== 3) return false;
  const [h, p, sig] = parts;
  if (h.length < 10 || p.length < 40 || sig.length < 10) return false;
  if (!parts.every((x) => /^[A-Za-z0-9_-]+$/.test(x))) return false;
  if (t.length < 100) return false;
  const header = decodeJwtSegmentBase64Url(h);
  const payload = decodeJwtSegmentBase64Url(p);
  if (header && /"alg"\s*:/.test(header) && /"(typ|kid)"\s*:/.test(header)) {
    if (/"typ"\s*:\s*"JWT"/i.test(header) || /"typ"\s*:\s*"at\+jwt"/i.test(header)) return true;
  }
  if (payload && payload.startsWith("{")) {
    if (
      /"(aud|iss|exp|iat|nbf|sub|oid|tid)"\s*:/.test(payload) &&
      (/"iss"\s*:\s*"https:\/\/(sts\.windows\.net|login\.microsoftonline\.com)/i.test(payload) ||
        /substrate\.office\.com/i.test(payload) ||
        /graph\.microsoft\.com/i.test(payload))
    ) {
      return true;
    }
  }
  return false;
}

function stringLooksLikeM365ClientTelemetry(text) {
  const t = String(text || "").trim();
  if (t.length < 50) return false;
  let score = 0;
  if (/SubstrateTraceId/i.test(t)) score += 2;
  if (/SubstrateLogicalId/i.test(t)) score += 2;
  if (/browserName/i.test(t) && /browserVersion/i.test(t)) score += 2;
  if (/cardCount/i.test(t)) score += 1;
  if (/cardReferenceIds/i.test(t) || /cardIds/i.test(t)) score += 1;
  if (/substrateLatency/i.test(t)) score += 1;
  if (/renderLatency/i.test(t)) score += 1;
  if (/isFallbackCards/i.test(t)) score += 1;
  if (/hasGptSelected/i.test(t)) score += 1;
  if (/displayType/i.test(t) && /"value"\s*:\s*"(grid|list)"/i.test(t)) score += 1;
  return score >= 4;
}

function stringLooksLikeBareUuidOrHexId(text) {
  const t = String(text || "").trim();
  if (!t) return true;
  const uuidShape = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  if (uuidShape.test(t)) return true;
  if (/^[0-9a-f]{32}$/i.test(t)) return true;
  const lines = t.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
  if (lines.length && lines.every((l) => uuidShape.test(l) || /^[0-9a-f]{32}$/i.test(l))) return true;
  const parts = t.split(/,\s*/).map((l) => l.trim()).filter(Boolean);
  if (
    parts.length >= 1 &&
    parts.length <= 6 &&
    parts.every((l) => uuidShape.test(l) || /^[0-9a-f]{32}$/i.test(l))
  )
    return true;
  if (t.startsWith("{") && t.length < 280) {
    if (
      /"(trace|correlation|event|request|session|logical)?id"\s*:\s*"[0-9a-f-]{32,36}"/i.test(t) &&
      !/"(text|content|message|markdown|answer)"\s*:/i.test(t)
    ) {
      return true;
    }
  }
  return false;
}

function networkExtractLooksLikeGarbage(text) {
  const t = (text || "").trim();
  if (t.length < 1) return true;
  if (stringLooksLikeJwt(t)) return true;
  if (stringLooksLikeM365ClientTelemetry(t)) return true;
  if (stringLooksLikeBareUuidOrHexId(t)) return true;
  if (/data:image\/[^;]+;base64,/i.test(t)) return true;
  if (t.length > 6_000) {
    const sample = t.slice(0, 12_000);
    let b64ish = 0;
    for (let i = 0; i < sample.length; i++) {
      const c = sample.charCodeAt(i);
      if (
        (c >= 65 && c <= 90) ||
        (c >= 97 && c <= 122) ||
        (c >= 48 && c <= 57) ||
        c === 43 ||
        c === 47 ||
        c === 61
      ) {
        b64ish++;
      }
    }
    if (b64ish / sample.length > 0.9) return true;
  }
  return false;
}

const COPILOT_TRANSIENT_STATUS_PATTERNS = [
  /Loading image/gi,
  /Image has been generated/gi,
];

function stripTransientCopilotStatus(text) {
  let cleaned = String(text ?? "");
  for (const pattern of COPILOT_TRANSIENT_STATUS_PATTERNS) {
    cleaned = cleaned.replace(pattern, "\n");
  }
  return cleaned;
}

function dedupeConsecutiveLines(text) {
  const lines = String(text ?? "").split(/\r?\n/);
  const out = [];
  let prev = null;
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      out.push("");
      prev = null;
      continue;
    }
    if (trimmed === prev) continue;
    out.push(trimmed);
    prev = trimmed;
  }
  return out.join("\n");
}

function dedupeConsecutiveParagraphs(text) {
  const parts = String(text ?? "").split(/\n{2,}/);
  const out = [];
  for (const part of parts) {
    const trimmed = part.trim();
    if (!trimmed) continue;
    if (out.at(-1) === trimmed) continue;
    out.push(trimmed);
  }
  return out.join("\n\n");
}

function normalizeCopilotVisibleText(text) {
  let cleaned = stripM365CopilotReplyChrome(String(text ?? ""));
  cleaned = stripStreamingPlaceholderTail(cleaned);
  cleaned = stripTransientCopilotStatus(cleaned);
  cleaned = dedupeConsecutiveLines(cleaned);
  cleaned = dedupeConsecutiveParagraphs(cleaned);
  return cleaned.trim();
}

async function pollCopilotGeneratingAndReply(session) {
  const r = await session
    .evaluate(copilotDomPollGeneratingAndReplyExpression())
    .catch(() => ({ value: { generating: false, reply: "" } }));
  const v = r?.value;
  const gen = v?.generating === true;
  const reply = stripM365CopilotReplyChrome(typeof v?.reply === "string" ? v.reply : "");
  return { generating: gen, reply };
}

async function extractAssistantReplyText(session) {
  const r = await session.evaluate(copilotDomReplyExtractIifeExpression()).catch(() => ({ value: "" }));
  return normalizeCopilotVisibleText(typeof r?.value === "string" ? r.value : "");
}

async function extractAssistantReplyStrict(session) {
  const r = await session.evaluate(`(() => {
    function visible(el) {
      return el && el.offsetParent !== null;
    }
    function inComposer(el) {
      return !!(el && el.closest(${JSON.stringify(COMPOSER_ANCESTOR_CLOSEST)}));
    }
    function inUserTurn(el) {
      if (!el) return false;
      try {
        if (el.closest('[data-message-author-role="user"]')) return true;
        if (el.closest('[data-message-author-role="User"]')) return true;
        if (el.closest('[data-testid="userMessage"]')) return true;
        if (el.closest('[data-testid*="user-message"]')) return true;
        if (el.closest('[data-testid*="UserMessage"]')) return true;
        if (el.matches && el.matches('cib-message[type="user"]')) return true;
        if (el.closest('[aria-label*="Your message"]')) return true;
        if (el.closest('[aria-label*="your message"]')) return true;
        if (el.closest('[aria-label*="送信した"]')) return true;
        if (el.closest('[aria-label*="自分のメッセージ"]')) return true;
        if (el.closest('[class*="fai-UserMessage"]')) return true;
        if (el.closest('[data-testid="chatQuestion"]')) return true;
      } catch (_) {}
      return false;
    }
    function walkElements(root, visit) {
      if (!root) return;
      if (root.nodeType === 1) visit(root);
      const tree = root.nodeType === 9 ? root.documentElement : root;
      if (!tree) return;
      const kids = tree.children || [];
      for (let i = 0; i < kids.length; i++) walkElements(kids[i], visit);
      if (tree.shadowRoot) walkElements(tree.shadowRoot, visit);
    }
    function queryDeepAll(selector, doc) {
      const top = doc.documentElement || doc.body;
      if (!top) return [];
      const out = [];
      walkElements(top, (el) => {
        try {
          if (el.matches && el.matches(selector)) out.push(el);
        } catch (_) {}
      });
      return out;
    }
    function extractFromDoc(doc) {
      const m365Replies = queryDeepAll('[data-testid="copilot-message-reply-div"]', doc).filter(
        (el) => visible(el) && !inComposer(el) && !inUserTurn(el),
      );
      if (m365Replies.length) {
        m365Replies.sort((a, b) => {
          const p = a.compareDocumentPosition(b);
          if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
          if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
          return 0;
        });
        const lastM365 = m365Replies[m365Replies.length - 1];
        const tm = (lastM365.innerText || lastM365.textContent || "").trim();
        if (tm.length > 0) return tm;
      }
      const byRole = [
        ...queryDeepAll('[data-message-author-role="assistant"]', doc),
        ...queryDeepAll('article[data-message-author-role="assistant"]', doc),
      ];
      const roots = [];
      for (const el of byRole) {
        if (!visible(el) || inComposer(el) || inUserTurn(el)) continue;
        const inner = byRole.some((other) => other !== el && other.contains(el));
        if (inner) continue;
        roots.push(el);
      }
      roots.sort((a, b) => {
        const p = a.compareDocumentPosition(b);
        if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
        if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
        return 0;
      });
      if (!roots.length) return "";
      const lastTurn = roots[roots.length - 1];
      return (lastTurn.innerText || lastTurn.textContent || "").trim();
    }
    function bestAcrossIframes(doc, depth) {
      let best = extractFromDoc(doc);
      if (depth > 8) return best;
      let frames;
      try {
        frames = doc.querySelectorAll("iframe");
      } catch (_) {
        return best;
      }
      for (const f of frames) {
        try {
          const c = f.contentDocument;
          if (c) {
            const inner = bestAcrossIframes(c, depth + 1);
            if (inner.length > best.length) best = inner;
          }
        } catch (_) {}
      }
      return best;
    }
    return bestAcrossIframes(document, 0);
  })()`).catch(() => ({ value: "" }));
  return normalizeCopilotVisibleText(typeof r?.value === "string" ? r.value : "");
}

async function extractAssistantReplyHeuristic(session) {
  const r = await session.evaluate(`(() => {
    function visible(el) {
      return el && el.offsetParent !== null;
    }
    function inComposer(el) {
      return !!(el && el.closest(${JSON.stringify(COMPOSER_ANCESTOR_CLOSEST)}));
    }
    function inUserTurn(el) {
      if (!el) return false;
      try {
        if (el.closest('[data-message-author-role="user"]')) return true;
        if (el.closest('[data-message-author-role="User"]')) return true;
        if (el.closest('[data-testid="userMessage"]')) return true;
        if (el.closest('[data-testid*="user-message"]')) return true;
        if (el.closest('[data-testid*="UserMessage"]')) return true;
        if (el.matches && el.matches('cib-message[type="user"]')) return true;
        if (el.closest('[aria-label*="Your message"]')) return true;
        if (el.closest('[aria-label*="your message"]')) return true;
        if (el.closest('[aria-label*="送信した"]')) return true;
        if (el.closest('[aria-label*="自分のメッセージ"]')) return true;
        if (el.closest('[class*="fai-UserMessage"]')) return true;
        if (el.closest('[data-testid="chatQuestion"]')) return true;
      } catch (_) {}
      return false;
    }
    function nodeText(el) {
      return (el.innerText || el.textContent || "").trim();
    }
    function walkElements(root, visit) {
      if (!root) return;
      if (root.nodeType === 1) visit(root);
      const tree = root.nodeType === 9 ? root.documentElement : root;
      if (!tree) return;
      const kids = tree.children || [];
      for (let i = 0; i < kids.length; i++) walkElements(kids[i], visit);
      if (tree.shadowRoot) walkElements(tree.shadowRoot, visit);
    }
    function queryDeepAll(selector, doc) {
      const top = doc.documentElement || doc.body;
      if (!top) return [];
      const out = [];
      walkElements(top, (el) => {
        try {
          if (el.matches && el.matches(selector)) out.push(el);
        } catch (_) {}
      });
      return out;
    }
    const selectors = [
      '[data-testid="copilot-message-reply-div"]',
      '[data-testid*="assistant-message"]',
      '[data-testid*="AssistantMessage"]',
      '[data-testid*="bot-message"]',
      '[data-conversation-role="assistant"]',
      '[data-participant="assistant"]',
      'cib-message[type="response"]',
      'cib-message[conversation="response"]',
      'cib-turn[type="response"]',
      '[class*="assistantMessage"]',
      '[class*="BotMessage"]',
    ];
    function extractFromDoc(doc) {
      const m365Replies = queryDeepAll('[data-testid="copilot-message-reply-div"]', doc).filter(
        (el) => visible(el) && !inComposer(el) && !inUserTurn(el),
      );
      if (m365Replies.length) {
        m365Replies.sort((a, b) => {
          const p = a.compareDocumentPosition(b);
          if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
          if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
          return 0;
        });
        const lastM365 = m365Replies[m365Replies.length - 1];
        const tm = nodeText(lastM365);
        if (tm.length > 0) return tm;
      }
      const dedup = new Set();
      const candidates = [];
      for (const s of selectors) {
        for (const el of queryDeepAll(s, doc)) {
          if (!el || dedup.has(el)) continue;
          dedup.add(el);
          if (!visible(el) || inComposer(el) || inUserTurn(el)) continue;
          const t = nodeText(el);
          if (t.length < 12) continue;
          candidates.push(el);
        }
      }
      if (!candidates.length) return "";
      candidates.sort((a, b) => {
        const p = a.compareDocumentPosition(b);
        if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
        if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
        return 0;
      });
      const last = candidates[candidates.length - 1];
      return nodeText(last);
    }
    function bestAcrossIframes(doc, depth) {
      let best = extractFromDoc(doc);
      if (depth > 8) return best;
      let frames;
      try {
        frames = doc.querySelectorAll("iframe");
      } catch (_) {
        return best;
      }
      for (const f of frames) {
        try {
          const c = f.contentDocument;
          if (c) {
            const inner = bestAcrossIframes(c, depth + 1);
            if (inner.length > best.length) best = inner;
          }
        } catch (_) {}
      }
      return best;
    }
    return bestAcrossIframes(document, 0);
  })()`).catch(() => ({ value: "" }));
  return normalizeCopilotVisibleText(typeof r?.value === "string" ? r.value : "");
}

/** Loose DOM extract length ≈ pasted prompt → still showing user wall, not a real assistant reply. */
function domExtractLooksLikeSubmittedPrompt(textLen, submittedLen) {
  if (!submittedLen || submittedLen < 1200) return false;
  const low = submittedLen * 0.72;
  const high = submittedLen * 1.2;
  return textLen >= low && textLen <= high;
}

async function resolveAssistantReplyForReturn(session, looseText, submittedPromptLen, netCapture = null) {
  const loose = normalizeCopilotVisibleText(looseText);
  if (!domExtractLooksLikeSubmittedPrompt(loose.length, submittedPromptLen)) return loose;
  const strict = normalizeCopilotVisibleText(await extractAssistantReplyStrict(session));
  if (strict.length >= 20 && strict.length < loose.length * 0.88) {
    console.error(
      "[copilot:response] prefer strict assistant over prompt-length loose extract strictLen=",
      strict.length,
      "looseLen=",
      loose.length,
      "submittedPromptLen=",
      submittedPromptLen,
    );
    return strict;
  }
  const heur = normalizeCopilotVisibleText(await extractAssistantReplyHeuristic(session));
  if (heur.length >= 15) {
    if (!domExtractLooksLikeSubmittedPrompt(heur.length, submittedPromptLen)) {
      console.error("[copilot:response] prefer heuristic assistant extract len=", heur.length);
      return heur;
    }
    if (heur.length < submittedPromptLen * 0.38) {
      console.error(
        "[copilot:response] heuristic assistant short vs submitted — accepting len=",
        heur.length,
      );
      return heur;
    }
  }
  if (netCapture) {
    try {
      if (typeof netCapture.pickAssistantFromChathubWs === "function") {
        const chw = normalizeCopilotVisibleText(netCapture.pickAssistantFromChathubWs());
        if (chw.length >= CHATHUB_ASSISTANT_MIN_CHARS && !networkExtractLooksLikeGarbage(chw)) {
          console.error("[copilot:response] M365 Chathub WebSocket assistant len=", chw.length);
          return chw;
        }
      }
      const shortN = normalizeCopilotVisibleText(
        await netCapture.pickBestShortAssistant(loose.length, submittedPromptLen),
      );
      if (shortN.length >= 20) {
        console.error("[copilot:response] network short-assistant len=", shortN.length);
        return shortN;
      }
      const nw = normalizeCopilotVisibleText(await netCapture.pickBestOver("", submittedPromptLen));
      if (
        nw.length >= CHATHUB_ASSISTANT_MIN_CHARS &&
        !networkExtractLooksLikeGarbage(nw) &&
        (!domExtractLooksLikeSubmittedPrompt(nw.length, submittedPromptLen) || nw.length < loose.length * 0.88)
      ) {
        console.error("[copilot:response] network pickBestOver(\"\") len=", nw.length);
        return nw;
      }
    } catch (e) {
      console.error("[copilot:response] network extract error:", e?.message || e);
    }
  }
  return null;
}

function normalizeProgressTextForUi(text, baselineText = "") {
  let cleaned = normalizeCopilotVisibleText(text);
  if (!cleaned) return "";

  const baseline = normalizeCopilotVisibleText(baselineText);
  if (!baseline) return cleaned;
  if (cleaned === baseline) return "";
  if (baseline.startsWith(cleaned)) return "";
  if (cleaned.startsWith(baseline)) {
    cleaned = stripStreamingPlaceholderTail(cleaned.slice(baseline.length).trimStart());
  }
  return cleaned;
}

async function waitForDomResponse(
  session,
  netCapture = null,
  submittedPromptLen = 0,
  abortCheck = null,
  options = {},
) {
  const onProgress = typeof options?.onProgress === "function" ? options.onProgress : null;
  let lastProgressText = "";
  const emitProgress = async (text, generating) => {
    if (!onProgress) return;
    const cleaned = normalizeProgressTextForUi(text, baselineProgressText);
    if (!cleaned) return;
    if (
      submittedPromptLen >= 1200 &&
      domExtractLooksLikeSubmittedPrompt(cleaned.length, submittedPromptLen)
    ) {
      return;
    }
    if (cleaned === lastProgressText) return;
    lastProgressText = cleaned;
    await onProgress({
      visibleText: cleaned,
      done: false,
      phase: generating ? "streaming" : "waiting",
      updatedAt: Date.now(),
    });
  };
  const wire = async (s) => {
    let t = normalizeCopilotVisibleText(s);
    if (netCapture) t = normalizeCopilotVisibleText(await netCapture.pickBestOver(t, submittedPromptLen) ?? "");
    return t;
  };

  await sleep(520);
  let baselineProgressText = normalizeCopilotVisibleText(
    (await pollCopilotGeneratingAndReply(session)).reply,
  );
  let baselineLen = baselineProgressText.length;
  /** If we captured the user's long prompt as "assistant", minDoneLen becomes unreachable (baseline+2 > len forever). */
  if (baselineLen > 12_000) {
    console.error(
      "[copilot:response] baseline assistant extract is huge (likely user bubble); resetting baseline for completion logic, was",
      baselineLen,
    );
    baselineProgressText = "";
    baselineLen = 0;
  }
  const waitStarted = Date.now();
  const timeoutMs =
    Number.isFinite(options?.timeoutMs) && options.timeoutMs > 0
      ? options.timeoutMs
      : RESPONSE_TIMEOUT_MS;
  const deadline = waitStarted + timeoutMs;
  let prev = baselineLen;
  let stable = 0;
  let streamed = false;
  /** When `RELAY_COPILOT_DEBUG_POLL=1`, periodic poll logs start ≥10s after this (avoids immediate spam with lastDiag=0). */
  let lastDiag = waitStarted;
  /** Consecutive polls with generating=false; used to finish sooner when the UI is idle but ticks were high. */
  let quietGen = 0;
  /** Phantom “stop generating” in DOM keeps this true forever — ignore after N seconds. */
  let genStreak = 0;
  /** M365 reply-div yields short answers (e.g. "OK"); keep floor low but still require growth vs baseline. */
  const minDoneLen = () =>
    Math.max(streamed ? 2 : 5, baselineLen + (streamed ? 1 : 5));

  while (Date.now() < deadline) {
    if (abortCheck && abortCheck()) {
      throw new Error("relay_copilot_aborted");
    }
    await sleep(RESPONSE_POLL_INTERVAL_MS);
    const { generating: generatingRaw, reply: replyRaw } = await pollCopilotGeneratingAndReply(session);
    const reply = normalizeCopilotVisibleText(replyRaw);
    const len = reply.length;

    if (generatingRaw) {
      genStreak++;
    } else {
      genStreak = 0;
    }
    const ignorePhantomStop = genStreak >= RESPONSE_PHANTOM_GENERATING_POLLS;
    const streamingPlaceholderTail = replyEndsWithStreamingPlaceholder(reply);
    const generating =
      streamingPlaceholderTail || (generatingRaw && !ignorePhantomStop);
    await emitProgress(reply, generating);
    if (generating) quietGen = 0;
    else quietGen++;
    if (ignorePhantomStop && genStreak === RESPONSE_PHANTOM_GENERATING_POLLS) {
      console.error(
        "[copilot:response] stop-button heuristic stuck; ignoring phantom generating after",
        RESPONSE_PHANTOM_GENERATING_POLLS,
        "polls (~",
        Math.round(
          (RESPONSE_PHANTOM_GENERATING_POLLS * RESPONSE_POLL_INTERVAL_MS) / 1000,
        ),
        "s)",
      );
    }

    if (process.env.RELAY_COPILOT_DEBUG_POLL === "1" && Date.now() - lastDiag > 10e3) {
      lastDiag = Date.now();
      let bodyLen = 0;
      try {
        const br = await session.evaluate(
          `(() => (document.body && document.body.innerText) ? document.body.innerText.length : 0)()`,
        );
        bodyLen = Number(br.value) || 0;
      } catch {
        /* ignore */
      }
      console.error("[copilot:response] poll", {
        elapsedSec: Math.floor((Date.now() - waitStarted) / 1000),
        timeoutInSec: Math.max(0, Math.floor((deadline - Date.now()) / 1000)),
        len,
        bodyLen,
        generating,
        generatingRaw,
        streamingPlaceholderTail,
        genStreak,
        streamed,
        stable,
        baselineLen,
      });
    }

    if (prev > 400 && len < prev * 0.15 && len < 800) {
      console.error("[copilot:response] baseline reset (new assistant bubble), prev=", prev, "len=", len);
      baselineLen = len;
      streamed = true;
      stable = 0;
      prev = len;
      continue;
    }

    if (len > baselineLen + 18) streamed = true;

    if (generating) {
      streamed = true;
      stable = 0;
      prev = len;
      continue;
    }

    if (len > prev + 5) {
      stable = 0;
      prev = len;
      continue;
    }

    const grewEnough =
      streamed ||
      len >= baselineLen + 10 ||
      len >= 120 ||
      len >= minDoneLen() ||
      (quietGen >= 5 && !generating && len > baselineLen && len >= 1);
    const settled = Math.abs(len - prev) <= 12;
    let needStableTicks = len > 220 ? 2 : 3;
    if (
      !generating &&
      quietGen >= 5 &&
      len >= Math.max(baselineLen + 6, 18) &&
      (streamed || len >= baselineLen + 8)
    ) {
      needStableTicks = Math.min(needStableTicks, 2);
    }
    const lengthOkForDone =
      (len >= minDoneLen() ||
        (quietGen >= 5 && !generating && len > baselineLen && len >= 1)) &&
      !streamingPlaceholderTail;
    if (settled && grewEnough && lengthOkForDone) {
      stable++;
      if (stable >= needStableTicks) {
        const postStableMs = len < 500 ? Math.min(750, RESPONSE_POST_STABLE_MS) : RESPONSE_POST_STABLE_MS;
        await sleep(postStableMs);
        const replyLate = normalizeCopilotVisibleText((await pollCopilotGeneratingAndReply(session)).reply);
        if (replyLate.length > len + 40) {
          console.error("[copilot:response] post-stable growth, keep waiting", len, "->", replyLate.length);
          stable = 0;
          prev = len;
          continue;
        }
        const candidate = replyLate.length >= len ? replyLate : reply;
        if (replyEndsWithStreamingPlaceholder(candidate)) {
          console.error("[copilot:response] post-stable reply still ends with streaming placeholder; keep waiting");
          stable = 0;
          prev = len;
          continue;
        }
        const out = await resolveAssistantReplyForReturn(session, candidate, submittedPromptLen, netCapture);
        if (out == null) {
          console.error(
            "[copilot:response] refuse false done: loose extract matches submitted prompt length but no strict assistant yet (submitted=",
            submittedPromptLen,
            "loose=",
            candidate.length,
            ")",
          );
          stable = 0;
          prev = len;
          continue;
        }
        console.error("[copilot:response] done, len=", out.length, "stable=", stable);
        return await wire(out);
      }
    } else {
      stable = 0;
    }

    /** Generation ended long ago but len stayed at a huge false positive — finish and return best strict assistant extract. */
    if (streamed && !generating && quietGen >= 14 && len > 8_000) {
      const strict = await extractAssistantReplyStrict(session);
      if (
        strict.length >= 12 &&
        strict.length < len * 0.85 &&
        (!domExtractLooksLikeSubmittedPrompt(strict.length, submittedPromptLen) || strict.length < len * 0.25)
      ) {
        console.error(
          "[copilot:response] done (quiet + strict assistant shorter than bogus len)",
          "strictLen=",
          strict.length,
          "domLen=",
          len,
        );
        return await wire(strict);
      }
    }

    /** DOM still looks like prompt echo — retry network/heuristic while Copilot has finished streaming. */
    if (
      netCapture &&
      streamed &&
      !generating &&
      domExtractLooksLikeSubmittedPrompt(len, submittedPromptLen) &&
      quietGen >= 4 &&
      quietGen % 4 === 0
    ) {
      const early = await resolveAssistantReplyForReturn(session, reply, submittedPromptLen, netCapture);
      if (early != null) {
        console.error("[copilot:response] done (resolved during echo wait) len=", early.length);
        return await wire(early);
      }
    }

    prev = len;
  }

  const fbLoose = normalizeCopilotVisibleText(await extractAssistantReplyText(session));
  const fbResolved = await resolveAssistantReplyForReturn(session, fbLoose, submittedPromptLen, netCapture);
  if (fbResolved != null) {
    console.error("[copilot:response] timeout, using resolved assistant len=", fbResolved.length);
    return await wire(fbResolved);
  }
  if (fbLoose.length >= 12 && !domExtractLooksLikeSubmittedPrompt(fbLoose.length, submittedPromptLen)) {
    console.error("[copilot:response] timeout, returning partial len=", fbLoose.length);
    return await wire(fbLoose);
  }
  if (fbLoose.length >= 12) {
    console.error(
      "[copilot:response] timeout, skipping prompt-echo loose extract (len=",
      fbLoose.length,
      ") — trying body/network",
    );
  }
  const bodyFb = await session.evaluate(`(() => {
    const raw = (document.body && document.body.innerText) ? document.body.innerText.trim() : "";
    if (raw.length < 80) return "";
    const nl = String.fromCharCode(10);
    const lines = raw.split(nl).map((l) => l.trim()).filter(Boolean);
    const tail = lines.slice(-40).join(nl);
    return tail.length > 200 ? tail.slice(-12e3) : "";
  })()`).catch(() => ({ value: "" }));
  const bodyStr = typeof bodyFb?.value === "string" ? bodyFb.value : "";
  if (bodyStr.length >= 80) {
    console.error("[copilot:response] timeout body tail fallback len=", bodyStr.length);
    return await wire(bodyStr);
  }
  if (netCapture) {
    const sn = normalizeCopilotVisibleText(
      await netCapture.pickBestShortAssistant(fbLoose.length, submittedPromptLen),
    );
    if (sn.length >= CHATHUB_ASSISTANT_MIN_CHARS) {
      console.error("[copilot:response] DOM empty; using network short-assistant len=", sn.length);
      return await wire(sn);
    }
    const nwTrim = normalizeCopilotVisibleText(await netCapture.pickBestOver("", submittedPromptLen));
    if (nwTrim.length >= CHATHUB_ASSISTANT_MIN_CHARS && !networkExtractLooksLikeGarbage(nwTrim)) {
      console.error("[copilot:response] DOM empty; using network-only len=", nwTrim.length);
      return await wire(nwTrim);
    }
  }
  throw new Error("Copilot response not found in DOM");
}

export {
  sleep,
  pollCopilotGeneratingAndReply,
  extractAssistantReplyStrict,
  extractAssistantReplyText,
  extractAssistantReplyHeuristic,
  domExtractLooksLikeSubmittedPrompt,
  normalizeCopilotVisibleText,
  normalizeProgressTextForUi,
  resolveAssistantReplyForReturn,
  waitForDomResponse,
};
