/**
 * waitForDomResponse — same logic as copilot_server.js (generated by build-copilot-dom-modules.mjs).
 */
import {
  ASSISTANT_REPLY_DOM_SELECTORS,
  COMPOSER_ANCESTOR_CLOSEST,
  M365_SUGGESTION_NOISE_SELECTORS,
  assistantTextHasStructuredContent,
  copilotDomPollGeneratingAndReplyExpression,
  copilotDomReplyExtractIifeExpression,
  shouldPreferExpandedAssistantTurn,
  stripM365CopilotReplyChrome,
  stripStreamingPlaceholderTail,
  replyEndsWithStreamingPlaceholder,
  replyIsOnlyReasoningDisclosurePlaceholder,
  CHATHUB_ASSISTANT_MIN_CHARS,
  RESPONSE_POLL_INTERVAL_MS,
  RESPONSE_TIMEOUT_MS,
  RESPONSE_PHANTOM_GENERATING_POLLS,
  RESPONSE_POST_STABLE_MS,
} from "./copilot_dom_poll.mjs";

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

function decodeJwtSegmentBase64Url(seg) {
  if (!seg || typeof seg !== "string") return "";
  try {
    const pad = (x) => x + "=".repeat((4 - (x.length % 4)) % 4);
    const b64 = pad(seg.replace(/-/g, "+").replace(/_/g, "/"));
    return Buffer.from(b64, "base64").toString("utf8");
  } catch {
    return "";
  }
}

function stringLooksLikeJwt(text) {
  const t = String(text || "").trim();
  const parts = t.split(".");
  if (parts.length !== 3) return false;
  const [h, p, sig] = parts;
  if (h.length < 10 || p.length < 40 || sig.length < 10) return false;
  if (!parts.every((x) => /^[A-Za-z0-9_-]+$/.test(x))) return false;
  if (t.length < 100) return false;
  const header = decodeJwtSegmentBase64Url(h);
  const payload = decodeJwtSegmentBase64Url(p);
  if (header && /"alg"\s*:/.test(header) && /"(typ|kid)"\s*:/.test(header)) {
    if (/"typ"\s*:\s*"JWT"/i.test(header) || /"typ"\s*:\s*"at\+jwt"/i.test(header)) return true;
  }
  if (payload && payload.startsWith("{")) {
    if (
      /"(aud|iss|exp|iat|nbf|sub|oid|tid)"\s*:/.test(payload) &&
      (/"iss"\s*:\s*"https:\/\/(sts\.windows\.net|login\.microsoftonline\.com)/i.test(payload) ||
        /substrate\.office\.com/i.test(payload) ||
        /graph\.microsoft\.com/i.test(payload))
    ) {
      return true;
    }
  }
  return false;
}

function stringLooksLikeM365ClientTelemetry(text) {
  const t = String(text || "").trim();
  if (t.length < 50) return false;
  let score = 0;
  if (/SubstrateTraceId/i.test(t)) score += 2;
  if (/SubstrateLogicalId/i.test(t)) score += 2;
  if (/browserName/i.test(t) && /browserVersion/i.test(t)) score += 2;
  if (/cardCount/i.test(t)) score += 1;
  if (/cardReferenceIds/i.test(t) || /cardIds/i.test(t)) score += 1;
  if (/substrateLatency/i.test(t)) score += 1;
  if (/renderLatency/i.test(t)) score += 1;
  if (/isFallbackCards/i.test(t)) score += 1;
  if (/hasGptSelected/i.test(t)) score += 1;
  if (/displayType/i.test(t) && /"value"\s*:\s*"(grid|list)"/i.test(t)) score += 1;
  return score >= 4;
}

function stringLooksLikeBareUuidOrHexId(text) {
  const t = String(text || "").trim();
  if (!t) return true;
  const uuidShape = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  if (uuidShape.test(t)) return true;
  if (/^[0-9a-f]{32}$/i.test(t)) return true;
  const lines = t.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
  if (lines.length && lines.every((l) => uuidShape.test(l) || /^[0-9a-f]{32}$/i.test(l))) return true;
  const parts = t.split(/,\s*/).map((l) => l.trim()).filter(Boolean);
  if (
    parts.length >= 1 &&
    parts.length <= 6 &&
    parts.every((l) => uuidShape.test(l) || /^[0-9a-f]{32}$/i.test(l))
  )
    return true;
  if (t.startsWith("{") && t.length < 280) {
    if (
      /"(trace|correlation|event|request|session|logical)?id"\s*:\s*"[0-9a-f-]{32,36}"/i.test(t) &&
      !/"(text|content|message|markdown|answer)"\s*:/i.test(t)
    ) {
      return true;
    }
  }
  return false;
}

function networkExtractLooksLikeGarbage(text) {
  const t = (text || "").trim();
  if (t.length < 1) return true;
  if (stringLooksLikeJwt(t)) return true;
  if (stringLooksLikeM365ClientTelemetry(t)) return true;
  if (stringLooksLikeBareUuidOrHexId(t)) return true;
  if (/data:image\/[^;]+;base64,/i.test(t)) return true;
  if (t.length > 6_000) {
    const sample = t.slice(0, 12_000);
    let b64ish = 0;
    for (let i = 0; i < sample.length; i++) {
      const c = sample.charCodeAt(i);
      if (
        (c >= 65 && c <= 90) ||
        (c >= 97 && c <= 122) ||
        (c >= 48 && c <= 57) ||
        c === 43 ||
        c === 47 ||
        c === 61
      ) {
        b64ish++;
      }
    }
    if (b64ish / sample.length > 0.9) return true;
  }
  return false;
}

const COPILOT_TRANSIENT_STATUS_PATTERNS = [
  /Loading image/gi,
  /Image has been generated/gi,
];

function stripTransientCopilotStatus(text) {
  let cleaned = String(text ?? "");
  for (const pattern of COPILOT_TRANSIENT_STATUS_PATTERNS) {
    cleaned = cleaned.replace(pattern, "\n");
  }
  return cleaned;
}

function normalizeReasoningDetectionText(text) {
  return String(text ?? "")
    .replace(/[*_`>#]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

function stripInternalReasoningLeadIns(text) {
  let cleaned = String(text ?? "").trimStart();
  cleaned = cleaned.replace(/^推論が\s*\d+\s*ステップで完了しました[:：]?\s*/u, "");
  cleaned = cleaned.replace(/^reasoning completed in\s*\d+\s*steps[:：]?\s*/i, "");
  cleaned = cleaned.replace(/^show\*+\s*considering[^*]{0,160}\*+\s*/i, "");
  cleaned = cleaned.replace(/^show\s*considering\s+/i, "");
  // Strip M365 disclosure toggle wrappers only when the remainder is non-empty
  // real content; otherwise `replyIsOnlyReasoningDisclosurePlaceholder` needs
  // the raw shape to stay intact so `waitForDomResponse` can keep polling.
  cleaned = cleaned.replace(
    /^Show\b[\s\S]{0,2000}?\bHide\b\s*(?=[^`\s])/,
    "",
  );
  return cleaned;
}

function looksLikeSearchProgressText(text) {
  const normalized = normalizeReasoningDetectionText(text);
  if (!normalized) return false;
  if (
    /\bget a quick answer\b/.test(normalized) ||
    /\bretrying searches\b/.test(normalized) ||
    /^(?:searches|get a quick answer)\b/.test(normalized)
  ) {
    return true;
  }
  if (/^(?:ok[, ]+)?i(?:'|’)?ll search\b/.test(normalized) || /^let me search\b/.test(normalized)) {
    return true;
  }
  if (
    /\bplanning to retry\b/.test(normalized) &&
    (/\bweb search\b/.test(normalized) || /\bsearch\b/.test(normalized))
  ) {
    return true;
  }
  if (
    /\bconduct(?:ing)? a web search\b/.test(normalized) ||
    /\bretrieving the expected results\b/.test(normalized)
  ) {
    return true;
  }
  return false;
}

function looksLikeInternalReasoningParagraph(text) {
  const raw = String(text ?? "").trim();
  if (!raw) return false;
  if (/^推論が\s*\d+\s*ステップで完了しました/u.test(raw)) return true;
  if (/^reasoning completed in\s*\d+\s*steps/i.test(raw)) return true;
  const normalized = normalizeReasoningDetectionText(raw);
  if (!normalized) return false;
  if (looksLikeSearchProgressText(normalized)) return true;
  if (/^the user wants me to\b/.test(normalized)) return true;
  if (/^show\s*considering\b/.test(normalized)) return true;
  if (
    /\bconsidering\b.*\b(search|tool|options|approach|next step|file)\b/.test(normalized) ||
    /\bi(?:'|’)?m evaluating the best approach\b/.test(normalized) ||
    /\bweighing the options\b/.test(normalized) ||
    /\bdetermining the approach\b/.test(normalized)
  ) {
    return true;
  }
  if (
    (/^i(?:'|’)?ll search\b/.test(normalized) ||
      /^let me search\b/.test(normalized) ||
      /^はい[、,]?\s*['"`].+['"`]\s*を検索します/.test(raw) ||
      /^['"`].+['"`]\s*を検索します/.test(raw)) &&
    /\b(search|websearch|office365_search)\b/.test(normalized)
  ) {
    return true;
  }
  if (
    (normalized.includes("office365_search") || normalized.includes("websearch")) &&
    (normalized.includes("search") || normalized.includes("citation") || normalized.includes("tool"))
  ) {
    return true;
  }
  return false;
}

function stripInternalReasoningParagraphs(text) {
  const cleaned = stripInternalReasoningLeadIns(text);
  const paragraphs = cleaned
    .split(/\n{2,}/)
    .map((part) => part.trim())
    .filter(Boolean)
    .filter((part) => !looksLikeInternalReasoningParagraph(part));
  return paragraphs.join("\n\n");
}

function dedupeConsecutiveLines(text) {
  const lines = String(text ?? "").split(/\r?\n/);
  const out = [];
  let prev = null;
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      out.push("");
      prev = null;
      continue;
    }
    if (trimmed === prev) continue;
    out.push(trimmed);
    prev = trimmed;
  }
  return out.join("\n");
}

function dedupeConsecutiveParagraphs(text) {
  const parts = String(text ?? "").split(/\n{2,}/);
  const out = [];
  for (const part of parts) {
    const trimmed = part.trim();
    if (!trimmed) continue;
    if (out.at(-1) === trimmed) continue;
    out.push(trimmed);
  }
  return out.join("\n\n");
}

function normalizeCopilotVisibleText(text) {
  let cleaned = stripM365CopilotReplyChrome(String(text ?? ""));
  cleaned = stripStreamingPlaceholderTail(cleaned);
  cleaned = stripTransientCopilotStatus(cleaned);
  cleaned = stripInternalReasoningParagraphs(cleaned);
  if (assistantTextHasStructuredContent(cleaned) || /relay_tool_call/u.test(cleaned)) {
    return cleaned.trim();
  }
  cleaned = dedupeConsecutiveLines(cleaned);
  cleaned = dedupeConsecutiveParagraphs(cleaned);
  return cleaned.trim();
}

function assistantReplyHasClosedFence(text) {
  const raw = String(text ?? "");
  const fences = raw.match(/```/g);
  return Array.isArray(fences) && fences.length >= 2 && fences.length % 2 === 0;
}

function hasBalancedStructuredPayload(text) {
  const raw = String(text ?? "");
  let depth = 0;
  let inString = false;
  let escape = false;
  let started = false;
  for (let i = 0; i < raw.length; i += 1) {
    const ch = raw[i];
    if (!started) {
      if (ch === "{" || ch === "[") {
        started = true;
        depth = 1;
      }
      continue;
    }
    if (inString) {
      if (escape) {
        escape = false;
      } else if (ch === "\\") {
        escape = true;
      } else if (ch === "\"") {
        inString = false;
      }
      continue;
    }
    if (ch === "\"") {
      inString = true;
      continue;
    }
    if (ch === "{" || ch === "[") {
      depth += 1;
      continue;
    }
    if (ch === "}" || ch === "]") {
      depth -= 1;
      if (depth === 0) {
        return true;
      }
    }
  }
  return false;
}

// Tool-shaped object keys the repair/fallback parsers recognize. When a short
// assistant reply is already an unbalanced JSON fragment starting with any of
// these keys, treat it as a still-streaming relay_tool call instead of a final
// answer so extraction keeps polling. Live capture 2026-04-17 (logged-in M365
// repair stage 1/3): Copilot returned just `{ "input": {` (12 chars). The old
// regex only triggered on `"name":`-first fragments, so the 12-char extract
// was accepted as the final assistant text and no write_file approval ever
// surfaced. Keep this list aligned with the tool-object key names the Rust
// side tolerates in `parse_initial`.
const INCOMPLETE_TOOL_KEY_RE =
  /"(?:name|input|path|content|arguments|parameters|relay_tool_call)"\s*:/u;

function assistantReplyLooksIncompleteRelayTool(text) {
  const cleaned = normalizeCopilotVisibleText(text);
  if (!cleaned) return false;
  const looksLikeToolShape =
    /relay_tool_call|```relay_tool/u.test(cleaned) ||
    (/^\s*[\[{]/u.test(cleaned) && INCOMPLETE_TOOL_KEY_RE.test(cleaned));
  if (!looksLikeToolShape) return false;
  if (assistantReplyHasClosedFence(cleaned) && hasBalancedStructuredPayload(cleaned)) return false;
  const sentinelIndex = cleaned.search(
    /relay_tool_call|"(?:name|input|path|content|arguments|parameters)"\s*:/u,
  );
  if (sentinelIndex < 0) return false;
  const objectStart = cleaned.lastIndexOf("{", sentinelIndex);
  const arrayStart = cleaned.lastIndexOf("[", sentinelIndex);
  const payloadStart = Math.max(objectStart, arrayStart);
  if (payloadStart < 0) return false;
  return !hasBalancedStructuredPayload(cleaned.slice(payloadStart));
}

function assistantReplyHasStrongCompletionSignal(text) {
  const cleaned = normalizeCopilotVisibleText(text);
  if (!cleaned || replyEndsWithStreamingPlaceholder(cleaned)) return false;
  if (replyIsOnlyReasoningDisclosurePlaceholder(cleaned)) return false;
  const looksLikeHtmlDocument = /<!doctype html>|<html\b/i.test(cleaned);
  if (looksLikeHtmlDocument) {
    return /<\/html>/i.test(cleaned);
  }
  if (assistantReplyLooksIncompleteRelayTool(cleaned)) return false;
  if (assistantReplyHasClosedFence(cleaned)) return true;
  if (assistantTextHasStructuredContent(cleaned) && cleaned.length >= 180) return true;
  return false;
}

const INTERNAL_PROGRESS_PREFIXES = [
  "the user wants me to ",
  "i'll ",
  "i will ",
  "let me ",
  "i need to ",
  "i should ",
  "i'm going to ",
  "first, i'll ",
  "first, i will ",
];

function looksLikeInternalDraftParagraph(text) {
  const normalized = String(text ?? "")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
  if (!normalized) return false;
  return (
    INTERNAL_PROGRESS_PREFIXES.some((prefix) => normalized.startsWith(prefix)) ||
    looksLikeInternalReasoningParagraph(text)
  );
}

function assistantTextQualityScore(text) {
  const cleaned = normalizeCopilotVisibleText(text);
  if (!cleaned) return -100;
  if (looksLikeSearchProgressText(cleaned)) return -80;
  let score = 0;
  if (cleaned.length >= 12) score += 2;
  if (cleaned.length >= 40) score += 1;
  if (/[。.!?]/u.test(cleaned)) score += 1;
  if (/\n/.test(cleaned)) score += 1;
  if (/```|`[^`]+`/.test(cleaned)) score += 1;
  if (!looksLikeInternalReasoningParagraph(cleaned)) score += 3;
  return score;
}

function shouldPreferAssistantText(candidate, baseline = "") {
  const next = normalizeCopilotVisibleText(candidate);
  const current = normalizeCopilotVisibleText(baseline);
  if (!next || looksLikeInternalReasoningParagraph(next) || looksLikeSearchProgressText(next)) return false;
  if (!current) return true;
  const nextScore = assistantTextQualityScore(next);
  const currentScore = assistantTextQualityScore(current);
  return (
    nextScore > currentScore ||
    (nextScore === currentScore &&
      next.length > current.length + Math.max(40, Math.floor(current.length * 0.35)))
  );
}

function assistantReplyAddsOnlySuggestionSuffix(candidate, baseline = "") {
  const next = normalizeCopilotVisibleText(candidate);
  const current = normalizeCopilotVisibleText(baseline);
  if (!next || !current || next === current || !next.startsWith(current)) return false;
  const suffix = next.slice(current.length).trim();
  if (!suffix) return false;
  if (assistantTextHasStructuredContent(suffix)) return false;
  if (assistantReplyHasStrongCompletionSignal(suffix)) return false;
  const lines = suffix.split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
  if (!lines.length || lines.length > 6) return false;
  return lines.every((line) => {
    if (line.length > 120) return false;
    if (/[?？]$/.test(line)) return true;
    if (/ください/u.test(line)) return true;
    if (/教えて/u.test(line)) return true;
    return /\b(?:same|meaning|example|examples|reply|respond|prompt|message|suggest)\b/i.test(line);
  });
}

function findProgressToolCutoff(text) {
  const raw = String(text ?? "");
  if (!raw) return -1;
  const candidates = [
    raw.indexOf("```relay_tool"),
    raw.indexOf("relay_tool_call"),
    raw.indexOf("```json"),
  ].filter((index) => index >= 0);
  for (const pattern of [
    /\n\s*\[\s*\{\s*"name"\s*:/u,
    /\n\s*\{\s*"name"\s*:/u,
    /\n\s*`?relay_tool`?/iu,
  ]) {
    const match = pattern.exec(raw);
    if (match?.index != null) {
      candidates.push(match.index);
    }
  }
  if (!candidates.length) return -1;
  return Math.min(...candidates);
}

function extractUserVisibleProgressText(text) {
  let cleaned = normalizeCopilotVisibleText(text);
  if (!cleaned) return "";
  if (looksLikeSearchProgressText(cleaned)) return "";

  const cutoff = findProgressToolCutoff(cleaned);
  if (cutoff >= 0) {
    cleaned = cleaned.slice(0, cutoff).trimEnd();
  }
  if (!cleaned) return "";

  const paragraphs = cleaned.split(/\n{2,}/).map((part) => part.trim()).filter(Boolean);
  while (paragraphs.length > 0 && looksLikeInternalDraftParagraph(paragraphs[0])) {
    paragraphs.shift();
  }
  cleaned = paragraphs.join("\n\n").trim();
  if (!cleaned) return "";

  if (looksLikeInternalDraftParagraph(cleaned)) {
    return "";
  }

  return cleaned;
}

async function pollCopilotGeneratingAndReply(session) {
  const r = await session
    .evaluate(copilotDomPollGeneratingAndReplyExpression())
    .catch(() => ({ value: { generating: false, reply: "" } }));
  const v = r?.value;
  const gen = v?.generating === true;
  const reply = stripM365CopilotReplyChrome(typeof v?.reply === "string" ? v.reply : "");
  const progressOnly = v?.progressOnly === true;
  const hasVisibleAssistantChat =
    typeof v?.hasVisibleAssistantChat === "boolean"
      ? v.hasVisibleAssistantChat
      : !!normalizeCopilotVisibleText(reply);
  return {
    generating: gen,
    reply,
    progressOnly,
    hasVisibleAssistantChat,
    hasExpandableCodeBlock: v?.hasExpandableCodeBlock === true,
  };
}

async function extractAssistantReplyText(session) {
  const r = await session.evaluate(copilotDomReplyExtractIifeExpression()).catch(() => ({ value: "" }));
  return normalizeCopilotVisibleText(typeof r?.value === "string" ? r.value : "");
}

async function extractAssistantReplyStructured(session) {
  return extractAssistantReplyText(session);
}

function assistantTurnExtractionIifeExpression({ includeGenericSelectors = true } = {}) {
  return `(() => {
    const includeGenericSelectors = ${includeGenericSelectors ? "true" : "false"};
    const suggestionSelectors = ${JSON.stringify(M365_SUGGESTION_NOISE_SELECTORS)};
    function visible(el) {
      return el && el.offsetParent !== null;
    }
    function inComposer(el) {
      return !!(el && el.closest(${JSON.stringify(COMPOSER_ANCESTOR_CLOSEST)}));
    }
    function inUserTurn(el) {
      if (!el) return false;
      try {
        if (el.closest('[data-message-author-role="user"]')) return true;
        if (el.closest('[data-message-author-role="User"]')) return true;
        if (el.closest('[data-testid="userMessage"]')) return true;
        if (el.closest('[data-testid*="user-message"]')) return true;
        if (el.closest('[data-testid*="UserMessage"]')) return true;
        if (el.matches && el.matches('cib-message[type="user"]')) return true;
        if (el.closest('[aria-label*="Your message"]')) return true;
        if (el.closest('[aria-label*="your message"]')) return true;
        if (el.closest('[aria-label*="送信した"]')) return true;
        if (el.closest('[aria-label*="自分のメッセージ"]')) return true;
        if (el.closest('[class*="fai-UserMessage"]')) return true;
        if (el.closest('[data-testid="chatQuestion"]')) return true;
      } catch (_) {}
      return false;
    }
    function nodeText(el) {
      if (!el) return "";
      let target = el;
      try {
        if (typeof el.cloneNode === "function") {
          target = el.cloneNode(true);
          const noisySelectors = [
            ".fai-CopilotMessage__footnote",
            ".fai-CopilotMessage__actions",
            ".scc-ChainOfThought",
            ".fai-SuggestionList",
            ".fai-Suggestion",
            ".fui-MessageBar",
            ".fai-Citation",
            ".fai-CitationCard",
            '[data-testid="chat-suggestion"]',
            '[data-citation-group-id]',
            '[data-grouped-citations]',
            '[data-testid="loading-message"]',
            '[data-testid="narrator-announcement"]',
            '[data-testid="sources-button-testid"]',
            '[data-testid*="source"]',
            '[data-testid*="Source"]',
            '[data-testid*="citation"]',
            '[data-testid*="Citation"]',
            '[data-testid="chat-response-message-disclaimer"]',
            '[data-testid="feedback-button-testid"]',
            '[data-testid="CopyButtonContainerTestId"]',
            '[data-testid="CopyButtonTestId"]',
            '[data-testid="overflow-menu-button"]',
            '[data-testid="SchedulePromptButtonTestId"]',
            '[data-testid="pages-split-button-primary"]',
            '[data-testid="pages-split-button-menu"]',
            '[data-testid="message-footer"]',
            '[data-testid="message-toolbar"]',
            '[class*="Citation"]',
            '[class*="citation"]',
            '[class*="Source"]',
            '[class*="source"]',
            '[class*="Footnote"]',
            '[class*="footnote"]',
            '[class*="Feedback"]',
            '[class*="feedback"]',
            '[class*="Toolbar"]',
            '[class*="toolbar"]',
          ];
          for (const selector of noisySelectors) {
            for (const node of target.querySelectorAll(selector)) {
              node.remove();
            }
          }
          for (const node of target.querySelectorAll('button, [role="button"], [role="menuitem"], [role="progressbar"], [role="toolbar"]')) {
            node.remove();
          }
        }
      } catch (_) {}
      return (target && (target.innerText || target.textContent) ? (target.innerText || target.textContent) : "").trim();
    }
    function isSuggestionToolbar(el) {
      if (!el || !el.getAttribute) return false;
      const role = (el.getAttribute("role") || "").toLowerCase();
      if (role !== "toolbar") return false;
      const label = [
        el.getAttribute("aria-label") || "",
        el.getAttribute("title") || "",
      ].join(" ").toLowerCase();
      return /\\bsuggestions?\\b/.test(label);
    }
    function isSuggestionNode(el) {
      if (!el || !el.closest) return false;
      try {
        for (const selector of suggestionSelectors) {
          if (el.matches?.(selector) || el.closest(selector)) return true;
        }
        const toolbar = el.matches?.('[role="toolbar"]') ? el : el.closest('[role="toolbar"]');
        return !!toolbar && isSuggestionToolbar(toolbar);
      } catch (_) {
        return false;
      }
    }
    function hasSuggestionSurfaceOutsideReply(container, replyRoot) {
      if (!container || !container.querySelectorAll) return false;
      try {
        const candidates = container.querySelectorAll(
          suggestionSelectors.join(", ") + ', [role="toolbar"]'
        );
        for (const node of candidates) {
          if (!visible(node)) continue;
          if (replyRoot && replyRoot.contains(node)) continue;
          if (isSuggestionNode(node)) return true;
        }
      } catch (_) {}
      return false;
    }
    function hasStructuredContent(text) {
      const s = String(text || "");
      return /\\\`\\\`\\\`/.test(s) || /^\\s*(?:[-*]|\\d+\\.)\\s+/m.test(s) || /^\\s*\\|.+\\|\\s*$/m.test(s);
    }
    function shouldPreferFullTurn(replyText, turnText) {
      const reply = nodeText({ innerText: replyText, textContent: replyText });
      const turn = nodeText({ innerText: turnText, textContent: turnText });
      if (!turn) return false;
      if (!reply) return true;
      const delta = turn.length - reply.length;
      if (delta < 20) return false;
      if (hasStructuredContent(turn) && !hasStructuredContent(reply)) return true;
      return delta >= Math.max(60, Math.floor(reply.length * 0.45));
    }
    function assistantRootScore(el) {
      if (!el || !el.getAttribute) return 0;
      let score = 0;
      const role =
        (el.getAttribute("data-message-author-role") ||
          el.getAttribute("data-conversation-role") ||
          el.getAttribute("data-participant") ||
          "").toLowerCase();
      const testid = (el.getAttribute("data-testid") || "").toLowerCase();
      const cls = String(el.className || "").toLowerCase();
      const tag = (el.tagName || "").toLowerCase();
      if (role === "assistant") score += 8;
      if (tag === "cib-message" && (el.getAttribute("type") || "").toLowerCase() === "response") score += 8;
      if (tag === "cib-turn" && (el.getAttribute("type") || "").toLowerCase() === "response") score += 8;
      if (/assistant|bot|copilot/.test(testid)) score += 5;
      if (/reply|message|turn|chat/.test(testid)) score += 2;
      if (/assistant|bot|copilot/.test(cls)) score += 4;
      if (/message|turn|chat/.test(cls)) score += 1;
      if (tag === "article") score += 1;
      return score;
    }
    function walkElements(root, visit) {
      if (!root) return;
      if (root.nodeType === 1) visit(root);
      const tree = root.nodeType === 9 ? root.documentElement : root;
      if (!tree) return;
      const kids = tree.children || [];
      for (let i = 0; i < kids.length; i++) walkElements(kids[i], visit);
      if (tree.shadowRoot) walkElements(tree.shadowRoot, visit);
    }
    function queryDeepAll(selector, doc) {
      const top = doc.documentElement || doc.body;
      if (!top) return [];
      const out = [];
      walkElements(top, (el) => {
        try {
          if (el.matches && el.matches(selector)) out.push(el);
        } catch (_) {}
      });
      return out;
    }
    function sortedVisibleAssistantRoots(doc) {
      const byRole = [...new Set([
        ...queryDeepAll('[data-message-author-role="assistant"]', doc),
        ...queryDeepAll('[data-conversation-role="assistant"]', doc),
        ...queryDeepAll('[data-participant="assistant"]', doc),
        ...queryDeepAll('article[data-message-author-role="assistant"]', doc),
        ...queryDeepAll('cib-message[type="response"]', doc),
        ...queryDeepAll('cib-turn[type="response"]', doc),
      ])];
      const roots = [];
      for (const el of byRole) {
        if (!visible(el) || inComposer(el) || inUserTurn(el)) continue;
        const inner = byRole.some((other) => other !== el && other.contains(el));
        if (inner) continue;
        roots.push(el);
      }
      roots.sort((a, b) => {
        const p = a.compareDocumentPosition(b);
        if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
        if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
        return 0;
      });
      return roots;
    }
    function findAssistantTurnRoot(el) {
      if (!el) return null;
      const replyLen = nodeText(el).length;
      const maxLen = Math.max(1200, replyLen * 12, replyLen + 16000);
      let best = el;
      let bestScore = assistantRootScore(el);
      let bestLen = replyLen;
      let cur = el;
      let depth = 0;
      while (cur && cur.parentElement && depth < 12) {
        cur = cur.parentElement;
        depth++;
        if (!visible(cur) || inComposer(cur) || inUserTurn(cur)) continue;
        const t = nodeText(cur);
        if (!t || t.length > maxLen) continue;
        if (hasSuggestionSurfaceOutsideReply(cur, el)) continue;
        const score = assistantRootScore(cur);
        if (score > bestScore || (score === bestScore && t.length > bestLen)) {
          best = cur;
          bestScore = score;
          bestLen = t.length;
        }
      }
      return best;
    }
    function extractFromDoc(doc) {
      const roots = sortedVisibleAssistantRoots(doc);
      if (roots.length) {
        const lastTurn = roots[roots.length - 1];
        const t = nodeText(lastTurn);
        if (t.length > 0) return t;
      }
      const m365Replies = queryDeepAll('[data-testid="copilot-message-reply-div"]', doc).filter(
        (el) => visible(el) && !inComposer(el) && !inUserTurn(el),
      );
      if (m365Replies.length) {
        m365Replies.sort((a, b) => {
          const p = a.compareDocumentPosition(b);
          if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
          if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
          return 0;
        });
        const lastM365 = m365Replies[m365Replies.length - 1];
        const replyText = nodeText(lastM365);
        const turnRoot = findAssistantTurnRoot(lastM365);
        const turnText = turnRoot ? nodeText(turnRoot) : "";
        if (shouldPreferFullTurn(replyText, turnText)) {
          return turnText;
        }
        if (replyText.length > 0) return replyText;
        if (turnText.length > 0) return turnText;
      }
      if (!includeGenericSelectors) return "";
      const selectors = ${JSON.stringify(ASSISTANT_REPLY_DOM_SELECTORS)};
      const dedup = new Set();
      const candidates = [];
      for (const s of selectors) {
        for (const el of queryDeepAll(s, doc)) {
          if (!el || dedup.has(el)) continue;
          dedup.add(el);
          if (!visible(el) || inComposer(el) || inUserTurn(el)) continue;
          const t = nodeText(el);
          if (t.length < 12) continue;
          candidates.push(el);
        }
      }
      if (!candidates.length) return "";
      candidates.sort((a, b) => {
        const p = a.compareDocumentPosition(b);
        if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
        if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
        return 0;
      });
      const last = candidates[candidates.length - 1];
      const fallbackText = nodeText(last);
      const turnRoot = findAssistantTurnRoot(last);
      const turnText = turnRoot ? nodeText(turnRoot) : "";
      if (shouldPreferFullTurn(fallbackText, turnText)) {
        return turnText;
      }
      return fallbackText;
    }
    function bestAcrossIframes(doc, depth) {
      let best = extractFromDoc(doc);
      if (depth > 8) return best;
      let frames;
      try {
        frames = doc.querySelectorAll("iframe");
      } catch (_) {
        return best;
      }
      for (const f of frames) {
        try {
          const c = f.contentDocument;
          if (c) {
            const inner = bestAcrossIframes(c, depth + 1);
            if (inner.length > best.length) best = inner;
          }
        } catch (_) {}
      }
      return best;
    }
    return bestAcrossIframes(document, 0);
  })()`;
}

async function extractAssistantReplyStrict(session) {
  const r = await session.evaluate(assistantTurnExtractionIifeExpression({
    includeGenericSelectors: false,
  })).catch(() => ({ value: "" }));
  return normalizeCopilotVisibleText(typeof r?.value === "string" ? r.value : "");
}

async function extractAssistantReplyHeuristic(session) {
  const r = await session.evaluate(assistantTurnExtractionIifeExpression({
    includeGenericSelectors: true,
  })).catch(() => ({ value: "" }));
  return normalizeCopilotVisibleText(typeof r?.value === "string" ? r.value : "");
}

/** Loose DOM extract length ≈ pasted prompt → still showing user wall, not a real assistant reply. */
function domExtractLooksLikeSubmittedPrompt(textLen, submittedLen) {
  if (!submittedLen || submittedLen < 1200) return false;
  const low = submittedLen * 0.72;
  const high = submittedLen * 1.2;
  return textLen >= low && textLen <= high;
}

function assistantReplyNeedsExpansionProbe(text, submittedPromptLen) {
  const cleaned = normalizeCopilotVisibleText(text);
  if (!cleaned) return true;
  if (looksLikeSearchProgressText(cleaned)) return true;
  if (assistantReplyLooksIncompleteRelayTool(cleaned)) return true;
  if (replyIsOnlyReasoningDisclosurePlaceholder(cleaned)) return true;
  if (domExtractLooksLikeSubmittedPrompt(cleaned.length, submittedPromptLen)) return true;
  return cleaned.length < 220 && !assistantTextHasStructuredContent(cleaned);
}

function copilotExpandLastAssistantTurnIifeExpression() {
  return `(() => {
    function visible(el) {
      return el && el.offsetParent !== null;
    }
    function inComposer(el) {
      return !!(el && el.closest(${JSON.stringify(COMPOSER_ANCESTOR_CLOSEST)}));
    }
    function inUserTurn(el) {
      if (!el) return false;
      try {
        if (el.closest('[data-message-author-role="user"]')) return true;
        if (el.closest('[data-message-author-role="User"]')) return true;
        if (el.closest('[data-testid="userMessage"]')) return true;
        if (el.closest('[data-testid*="user-message"]')) return true;
        if (el.closest('[data-testid*="UserMessage"]')) return true;
        if (el.matches && el.matches('cib-message[type="user"]')) return true;
        if (el.closest('[aria-label*="Your message"]')) return true;
        if (el.closest('[aria-label*="your message"]')) return true;
        if (el.closest('[aria-label*="送信した"]')) return true;
        if (el.closest('[aria-label*="自分のメッセージ"]')) return true;
        if (el.closest('[class*="fai-UserMessage"]')) return true;
        if (el.closest('[data-testid="chatQuestion"]')) return true;
      } catch (_) {}
      return false;
    }
    function walkElements(root, visit) {
      if (!root) return;
      if (root.nodeType === 1) visit(root);
      const tree = root.nodeType === 9 ? root.documentElement : root;
      if (!tree) return;
      const kids = tree.children || [];
      for (let i = 0; i < kids.length; i++) walkElements(kids[i], visit);
      if (tree.shadowRoot) walkElements(tree.shadowRoot, visit);
    }
    function queryDeepAll(selector, root) {
      const top = root?.nodeType === 9 ? (root.documentElement || root.body) : root;
      if (!top) return [];
      const out = [];
      walkElements(top, (el) => {
        try {
          if (el.matches && el.matches(selector)) out.push(el);
        } catch (_) {}
      });
      return out;
    }
    function nodeText(el) {
      return (el && (el.innerText || el.textContent) ? (el.innerText || el.textContent) : "").trim();
    }
    function matchesShowMoreControl(el) {
      const text = [
        nodeText(el),
        el?.getAttribute?.("aria-label") || "",
        el?.getAttribute?.("title") || "",
      ].join(" ").toLowerCase();
      return /show more lines|show more|もっと表示/.test(text);
    }
    const roots = queryDeepAll('[data-testid="copilot-message-reply-div"]', document).filter(
      (el) => visible(el) && !inComposer(el) && !inUserTurn(el),
    );
    if (!roots.length) return { clicked: false };
    roots.sort((a, b) => {
      const p = a.compareDocumentPosition(b);
      if (p & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
      if (p & Node.DOCUMENT_POSITION_PRECEDING) return 1;
      return 0;
    });
    const root = roots[roots.length - 1];
    const buttons = queryDeepAll('button, [role="button"]', root).filter(
      (el) => visible(el) && matchesShowMoreControl(el),
    );
    if (!buttons.length) return { clicked: false };
    buttons[0].click();
    return { clicked: true, label: nodeText(buttons[0]) };
  })()`;
}

async function expandLastAssistantTurnIfNeeded(session) {
  const r = await session.evaluate(copilotExpandLastAssistantTurnIifeExpression()).catch(() => ({ value: { clicked: false } }));
  return r?.value?.clicked === true;
}

async function resolveAssistantReplyForReturn(session, looseText, submittedPromptLen, netCapture = null) {
  const loose = normalizeCopilotVisibleText(looseText);
  const looseLooksLikePrompt = domExtractLooksLikeSubmittedPrompt(loose.length, submittedPromptLen);
  const needsExpansionProbe = assistantReplyNeedsExpansionProbe(loose, submittedPromptLen);
  const structured = normalizeCopilotVisibleText(await extractAssistantReplyStructured(session));
  const structuredLooksLikePrompt = domExtractLooksLikeSubmittedPrompt(structured.length, submittedPromptLen);
  const structuredNeedsExpansionProbe = assistantReplyNeedsExpansionProbe(structured, submittedPromptLen);
  const strict = normalizeCopilotVisibleText(await extractAssistantReplyStrict(session));
  const strictLooksLikePrompt = domExtractLooksLikeSubmittedPrompt(strict.length, submittedPromptLen);
  const strictNeedsExpansionProbe = assistantReplyNeedsExpansionProbe(strict, submittedPromptLen);
  const strictAddsOnlySuggestionSuffix =
    !!strict &&
    !!structured &&
    assistantReplyAddsOnlySuggestionSuffix(strict, structured);
  const strictClearlyMoreCompleteThanStructured =
    !!strict &&
    !strictLooksLikePrompt &&
    !strictAddsOnlySuggestionSuffix &&
    (!!structured &&
      !structuredLooksLikePrompt &&
      ((assistantReplyHasStrongCompletionSignal(strict) &&
        !assistantReplyHasStrongCompletionSignal(structured)) ||
        shouldPreferExpandedAssistantTurn(structured, strict) ||
        (strict.startsWith(structured) && strict.length >= structured.length + 10)));
  if (strictClearlyMoreCompleteThanStructured) return strict;
  if (structured && !structuredLooksLikePrompt && !structuredNeedsExpansionProbe) return structured;
  if (strict && !strictLooksLikePrompt && !strictNeedsExpansionProbe) return strict;
  if (!strict && !looseLooksLikePrompt && !needsExpansionProbe) return loose;

  let best = "";
  const acceptCandidate = (label, rawCandidate, { allowPromptBand = false } = {}) => {
    const candidate = normalizeCopilotVisibleText(rawCandidate);
    if (!candidate) return false;
    if (networkExtractLooksLikeGarbage(candidate)) return false;
    if (looksLikeSearchProgressText(candidate)) return false;
    if (assistantReplyLooksIncompleteRelayTool(candidate)) return false;
    if (replyIsOnlyReasoningDisclosurePlaceholder(candidate)) return false;
    if (structured && assistantReplyAddsOnlySuggestionSuffix(candidate, structured)) {
      return false;
    }
    if (!allowPromptBand && domExtractLooksLikeSubmittedPrompt(candidate.length, submittedPromptLen)) {
      return false;
    }
    if (!best) {
      console.error(`[copilot:response] ${label} len=`, candidate.length);
      best = candidate;
      return true;
    }
    if (
      shouldPreferExpandedAssistantTurn(best, candidate) ||
      shouldPreferAssistantText(candidate, best)
    ) {
      console.error(`[copilot:response] ${label} len=`, candidate.length);
      best = candidate;
      return true;
    }
    return false;
  };

  if (structured && !structuredLooksLikePrompt) {
    acceptCandidate("prefer structured assistant extract", structured);
  }
  if (strict && !strictLooksLikePrompt) {
    acceptCandidate("prefer strict assistant extract", strict);
  } else if (!looseLooksLikePrompt) {
    acceptCandidate("prefer loose assistant extract", loose);
  }
  if (!best || assistantReplyNeedsExpansionProbe(best, submittedPromptLen)) {
    const heur = normalizeCopilotVisibleText(await extractAssistantReplyHeuristic(session));
    acceptCandidate("prefer heuristic assistant extract", heur);
  }
  if (netCapture && (!best || assistantReplyNeedsExpansionProbe(best, submittedPromptLen))) {
    try {
      if (typeof netCapture.pickAssistantFromChathubWs === "function") {
        const chw = normalizeCopilotVisibleText(netCapture.pickAssistantFromChathubWs());
        if (chw.length >= CHATHUB_ASSISTANT_MIN_CHARS) {
          acceptCandidate("M365 Chathub WebSocket assistant", chw);
        }
      }
      const shortN = normalizeCopilotVisibleText(
        await netCapture.pickBestShortAssistant(loose.length, submittedPromptLen),
      );
      if (shortN.length >= 20) acceptCandidate("network short-assistant", shortN);
      const nw = normalizeCopilotVisibleText(await netCapture.pickBestOver("", submittedPromptLen));
      if (nw.length >= CHATHUB_ASSISTANT_MIN_CHARS) {
        acceptCandidate("network pickBestOver(\"\")", nw, {
          allowPromptBand: nw.length < loose.length * 0.88,
        });
      }
    } catch (e) {
      console.error("[copilot:response] network extract error:", e?.message || e);
    }
  }
  if (best) return best;
  if (assistantReplyLooksIncompleteRelayTool(loose)) return null;
  return looseLooksLikePrompt ? null : loose;
}

function normalizeProgressTextForUi(text, baselineText = "") {
  let cleaned = extractUserVisibleProgressText(text);
  if (!cleaned) return "";

  const baseline = extractUserVisibleProgressText(baselineText);
  if (!baseline) return cleaned;
  if (cleaned === baseline) return "";
  if (baseline.startsWith(cleaned)) return "";
  if (cleaned.startsWith(baseline)) {
    cleaned = stripStreamingPlaceholderTail(cleaned.slice(baseline.length).trimStart());
  }
  return cleaned;
}

async function waitForDomResponse(
  session,
  netCapture = null,
  submittedPromptLen = 0,
  abortCheck = null,
  options = {},
) {
  const onProgress = typeof options?.onProgress === "function" ? options.onProgress : null;
  const onFinalize = typeof options?.onFinalize === "function" ? options.onFinalize : null;
  let lastProgressText = "";
  const finalize = async (mode, text) => {
    if (onFinalize) {
      await onFinalize({
        mode,
        textLength: String(text ?? "").length,
      });
    }
    return await wire(text);
  };
  const emitProgress = async (text, generating) => {
    if (!onProgress) return;
    const cleaned = normalizeProgressTextForUi(text, baselineProgressText);
    if (!cleaned) return;
    if (
      submittedPromptLen >= 1200 &&
      domExtractLooksLikeSubmittedPrompt(cleaned.length, submittedPromptLen)
    ) {
      return;
    }
    if (cleaned === lastProgressText) return;
    lastProgressText = cleaned;
    await onProgress({
      visibleText: cleaned,
      done: false,
      phase: generating ? "streaming" : "waiting",
      updatedAt: Date.now(),
    });
  };
  const wire = async (s) => {
    const dom = normalizeCopilotVisibleText(s);
    if (dom || !netCapture) return dom;
    const networkCandidate = normalizeCopilotVisibleText(
      (await netCapture.pickBestOver(dom, submittedPromptLen)) ?? "",
    );
    return shouldPreferAssistantText(networkCandidate, "") ? networkCandidate : dom;
  };

  await sleep(520);
  const baselineState = await pollCopilotGeneratingAndReply(session);
  let baselineProgressText = normalizeCopilotVisibleText(baselineState.reply);
  let baselineLen = baselineProgressText.length;
  /** If we captured the user's long prompt as "assistant", minDoneLen becomes unreachable (baseline+2 > len forever). */
  if (baselineLen > 12_000) {
    console.error(
      "[copilot:response] baseline assistant extract is huge (likely user bubble); resetting baseline for completion logic, was",
      baselineLen,
    );
    baselineProgressText = "";
    baselineLen = 0;
  }
  const waitStarted = Date.now();
  const timeoutMs =
    Number.isFinite(options?.timeoutMs) && options.timeoutMs > 0
      ? options.timeoutMs
      : RESPONSE_TIMEOUT_MS;
  const deadline = waitStarted + timeoutMs;
  let prev = baselineLen;
  let stable = 0;
  let streamed = false;
  /** When `RELAY_COPILOT_DEBUG_POLL=1`, periodic poll logs start ≥10s after this (avoids immediate spam with lastDiag=0). */
  let lastDiag = waitStarted;
  /** Consecutive polls with generating=false; used to finish sooner when the UI is idle but ticks were high. */
  let quietGen = 0;
  /** Phantom “stop generating” in DOM keeps this true forever — ignore after N seconds. */
  let genStreak = 0;
  /** Long code replies may hide trailing lines behind a one-shot expansion control. */
  let expandAttempted = false;
  /** M365 reply-div yields short answers (e.g. "OK"); keep floor low but still require growth vs baseline. */
  const minDoneLen = () =>
    Math.max(streamed ? 2 : 5, baselineLen + (streamed ? 1 : 5));

  while (Date.now() < deadline) {
    if (abortCheck && abortCheck()) {
      throw new Error("relay_copilot_aborted");
    }
    await sleep(RESPONSE_POLL_INTERVAL_MS);
    const {
      generating: generatingRaw,
      reply: replyRaw,
      progressOnly,
      hasVisibleAssistantChat,
      hasExpandableCodeBlock,
    } = await pollCopilotGeneratingAndReply(session);
    const reply = normalizeCopilotVisibleText(replyRaw);
    const len = reply.length;

    if (generatingRaw) {
      genStreak++;
    } else {
      genStreak = 0;
    }
    const ignorePhantomStop = genStreak >= RESPONSE_PHANTOM_GENERATING_POLLS;
    const streamingPlaceholderTail = replyEndsWithStreamingPlaceholder(reply);
    const reasoningDisclosurePlaceholder = replyIsOnlyReasoningDisclosurePlaceholder(reply);
    const generating =
      streamingPlaceholderTail ||
      reasoningDisclosurePlaceholder ||
      (generatingRaw && !ignorePhantomStop);
    await emitProgress(reply, generating || progressOnly);
    if (generating) quietGen = 0;
    else quietGen++;
    if (ignorePhantomStop && genStreak === RESPONSE_PHANTOM_GENERATING_POLLS) {
      console.error(
        "[copilot:response] stop-button heuristic stuck; ignoring phantom generating after",
        RESPONSE_PHANTOM_GENERATING_POLLS,
        "polls (~",
        Math.round(
          (RESPONSE_PHANTOM_GENERATING_POLLS * RESPONSE_POLL_INTERVAL_MS) / 1000,
        ),
        "s)",
      );
    }

    if (process.env.RELAY_COPILOT_DEBUG_POLL === "1" && Date.now() - lastDiag > 10e3) {
      lastDiag = Date.now();
      let bodyLen = 0;
      try {
        const br = await session.evaluate(
          `(() => (document.body && document.body.innerText) ? document.body.innerText.length : 0)()`,
        );
        bodyLen = Number(br.value) || 0;
      } catch {
        /* ignore */
      }
      console.error("[copilot:response] poll", {
        elapsedSec: Math.floor((Date.now() - waitStarted) / 1000),
        timeoutInSec: Math.max(0, Math.floor((deadline - Date.now()) / 1000)),
        len,
        bodyLen,
        generating,
        generatingRaw,
        streamingPlaceholderTail,
        genStreak,
        streamed,
        stable,
        baselineLen,
      });
    }

    if (prev > 400 && len < prev * 0.15 && len < 800) {
      console.error("[copilot:response] baseline reset (new assistant bubble), prev=", prev, "len=", len);
      baselineLen = len;
      streamed = true;
      stable = 0;
      prev = len;
      continue;
    }

    if (len > baselineLen + 18) streamed = true;

    if (progressOnly || !hasVisibleAssistantChat) {
      streamed = true;
      stable = 0;
      prev = len;
      continue;
    }

    if (
      !generating &&
      !expandAttempted &&
      (hasExpandableCodeBlock || assistantReplyLooksIncompleteRelayTool(reply))
    ) {
      const expanded = await expandLastAssistantTurnIfNeeded(session);
      expandAttempted = expanded;
      if (expanded) {
        console.error("[copilot:response] expanded last assistant turn for hidden code");
        await sleep(450);
        stable = 0;
        prev = len;
        continue;
      }
    }

    if (generating) {
      streamed = true;
      stable = 0;
      prev = len;
      continue;
    }

    if (len > prev + 5) {
      stable = 0;
      prev = len;
      continue;
    }

    const grewEnough =
      streamed ||
      len >= baselineLen + 10 ||
      len >= 120 ||
      len >= minDoneLen() ||
      (quietGen >= 5 && !generating && len > baselineLen && len >= 1);
    const settled = Math.abs(len - prev) <= 12;
    let needStableTicks = len > 220 ? 2 : 3;
    if (
      !generating &&
      quietGen >= 5 &&
      len >= Math.max(baselineLen + 6, 18) &&
      (streamed || len >= baselineLen + 8)
    ) {
      needStableTicks = Math.min(needStableTicks, 2);
    }
    const lengthOkForDone =
      (len >= minDoneLen() ||
        (quietGen >= 5 && !generating && len > baselineLen && len >= 1)) &&
      !streamingPlaceholderTail;
    if (settled && grewEnough && lengthOkForDone) {
      stable++;
      if (stable >= needStableTicks) {
        const postStableMs = len < 500 ? Math.min(750, RESPONSE_POST_STABLE_MS) : RESPONSE_POST_STABLE_MS;
        await sleep(postStableMs);
        const lateState = await pollCopilotGeneratingAndReply(session);
        const replyLate = normalizeCopilotVisibleText(lateState.reply);
        if (replyLate.length > len + 40) {
          console.error("[copilot:response] post-stable growth, keep waiting", len, "->", replyLate.length);
          stable = 0;
          prev = len;
          continue;
        }
        if (lateState.progressOnly || !lateState.hasVisibleAssistantChat) {
          console.error("[copilot:response] post-stable state is still progress-only; keep waiting");
          stable = 0;
          prev = replyLate.length;
          continue;
        }
        if (
          lateState.hasExpandableCodeBlock ||
          /\bshow more lines\b/i.test(replyLate) ||
          assistantReplyLooksIncompleteRelayTool(replyLate)
        ) {
          const expanded = await expandLastAssistantTurnIfNeeded(session);
          if (expanded) {
            console.error("[copilot:response] expanded last assistant turn for hidden code");
            await sleep(450);
            stable = 0;
            prev = replyLate.length;
            continue;
          }
        }
        const candidate = replyLate.length >= len ? replyLate : reply;
        if (replyEndsWithStreamingPlaceholder(candidate)) {
          console.error("[copilot:response] post-stable reply still ends with streaming placeholder; keep waiting");
          stable = 0;
          prev = len;
          continue;
        }
        if (replyIsOnlyReasoningDisclosurePlaceholder(candidate)) {
          console.error("[copilot:response] post-stable reply is only a reasoning disclosure placeholder; keep waiting");
          stable = 0;
          prev = len;
          continue;
        }
        const out = await resolveAssistantReplyForReturn(session, candidate, submittedPromptLen, netCapture);
        if (out == null) {
          console.error(
            "[copilot:response] refuse false done: loose extract matches submitted prompt length but no strict assistant yet (submitted=",
            submittedPromptLen,
            "loose=",
            candidate.length,
            ")",
          );
          stable = 0;
          prev = len;
          continue;
        }
        console.error("[copilot:response] done, len=", out.length, "stable=", stable);
        return await finalize("stable_resolved", out);
      }
    } else {
      stable = 0;
    }

    if (
      !generating &&
      !progressOnly &&
      hasVisibleAssistantChat &&
      (ignorePhantomStop || quietGen >= 5) &&
      (streamed || len >= baselineLen + 8 || len >= 120)
    ) {
      const earlyResolved = await resolveAssistantReplyForReturn(session, reply, submittedPromptLen, netCapture);
      if (earlyResolved != null && assistantReplyHasStrongCompletionSignal(earlyResolved)) {
        console.error(
          "[copilot:response] done (strong structured reply after stalled generating) len=",
          earlyResolved.length,
        );
        return await finalize("stable_strong_signal", earlyResolved);
      }
    }

    /** Generation ended long ago but len stayed at a huge false positive — finish and return best strict assistant extract. */
    if (streamed && !generating && quietGen >= 14 && len > 8_000) {
      const strict = await extractAssistantReplyStrict(session);
      if (
        strict.length >= 12 &&
        strict.length < len * 0.85 &&
        (!domExtractLooksLikeSubmittedPrompt(strict.length, submittedPromptLen) || strict.length < len * 0.25)
      ) {
        console.error(
          "[copilot:response] done (quiet + strict assistant shorter than bogus len)",
          "strictLen=",
          strict.length,
          "domLen=",
          len,
        );
        return await finalize("stable_quiet_strict", strict);
      }
    }

    /** DOM still looks like prompt echo — retry network/heuristic while Copilot has finished streaming. */
    if (
      netCapture &&
      streamed &&
      !generating &&
      domExtractLooksLikeSubmittedPrompt(len, submittedPromptLen) &&
      quietGen >= 4 &&
      quietGen % 4 === 0
    ) {
      const early = await resolveAssistantReplyForReturn(session, reply, submittedPromptLen, netCapture);
      if (early != null) {
        console.error("[copilot:response] done (resolved during echo wait) len=", early.length);
        return await finalize("stable_echo_wait", early);
      }
    }

    prev = len;
  }

  const fbLoose = normalizeCopilotVisibleText(await extractAssistantReplyText(session));
  const fbResolved = await resolveAssistantReplyForReturn(session, fbLoose, submittedPromptLen, netCapture);
  if (fbResolved != null) {
    console.error("[copilot:response] timeout, using resolved assistant len=", fbResolved.length);
    return await finalize("timeout_resolved", fbResolved);
  }
  if (fbLoose.length >= 12 && !domExtractLooksLikeSubmittedPrompt(fbLoose.length, submittedPromptLen)) {
    console.error("[copilot:response] timeout, returning partial len=", fbLoose.length);
    return await finalize("timeout_partial", fbLoose);
  }
  if (fbLoose.length >= 12) {
    console.error(
      "[copilot:response] timeout, skipping prompt-echo loose extract (len=",
      fbLoose.length,
      ") — trying body/network",
    );
  }
  const bodyFb = await session.evaluate(`(() => {
    const raw = (document.body && document.body.innerText) ? document.body.innerText.trim() : "";
    if (raw.length < 80) return "";
    const nl = String.fromCharCode(10);
    const lines = raw.split(nl).map((l) => l.trim()).filter(Boolean);
    const tail = lines.slice(-40).join(nl);
    return tail.length > 200 ? tail.slice(-12e3) : "";
  })()`).catch(() => ({ value: "" }));
  const bodyStr = typeof bodyFb?.value === "string" ? bodyFb.value : "";
  if (bodyStr.length >= 80) {
    console.error("[copilot:response] timeout body tail fallback len=", bodyStr.length);
    return await finalize("timeout_body_tail", bodyStr);
  }
  if (netCapture) {
    const sn = normalizeCopilotVisibleText(
      await netCapture.pickBestShortAssistant(fbLoose.length, submittedPromptLen),
    );
    if (sn.length >= CHATHUB_ASSISTANT_MIN_CHARS) {
      console.error("[copilot:response] DOM empty; using network short-assistant len=", sn.length);
      return await finalize("timeout_network_short", sn);
    }
    const nwTrim = normalizeCopilotVisibleText(await netCapture.pickBestOver("", submittedPromptLen));
    if (nwTrim.length >= CHATHUB_ASSISTANT_MIN_CHARS && !networkExtractLooksLikeGarbage(nwTrim)) {
      console.error("[copilot:response] DOM empty; using network-only len=", nwTrim.length);
      return await finalize("timeout_network_only", nwTrim);
    }
  }
  throw new Error("Copilot response not found in DOM");
}

export {
  sleep,
  pollCopilotGeneratingAndReply,
  extractAssistantReplyStructured,
  extractAssistantReplyStrict,
  extractAssistantReplyText,
  extractAssistantReplyHeuristic,
  assistantReplyHasStrongCompletionSignal,
  assistantReplyAddsOnlySuggestionSuffix,
  domExtractLooksLikeSubmittedPrompt,
  normalizeCopilotVisibleText,
  normalizeProgressTextForUi,
  resolveAssistantReplyForReturn,
  waitForDomResponse,
};
