import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const validationDoc = readFileSync("docs/AIONUI_WINDOWS_VALIDATION.md", "utf8");
const signingDoc = readFileSync("docs/TRUSTED_SIGNING_SETUP.md", "utf8");
const selfSignedDoc = readFileSync("docs/WINDOWS_SELF_SIGNED_SIGNING.md", "utf8");

test("AionUi Windows validation checklist covers install, provider, tools, and Office workflows", () => {
  assert.match(validationDoc, /release-aionui-windows-installer\.yml/);
  assert.match(validationDoc, /no administrator rights/i);
  assert.match(validationDoc, /Relay\.Agent-\*-win-x64\*\.exe/);
  assert.match(validationDoc, /Relay\.Agent-AionUi-release-manifest\.json/);
  assert.match(validationDoc, /RelayAionUiReleaseArtifactManifest\.v1/);
  assert.match(validationDoc, /relay-aionui-overlay-v1/);
  assert.match(validationDoc, /bundled ripgrep payload/);
  assert.match(validationDoc, /standalone Node\/LiteParse are not bundled/);
  assert.match(validationDoc, /Get-AuthenticodeSignature/);
  assert.match(validationDoc, /Defender/);
  assert.match(validationDoc, /Relay Agent \/ M365 Copilot/);
  assert.match(validationDoc, /relay-agent\/m365-copilot/);
  assert.match(validationDoc, /OfficeCLI downloads into a user-local Relay-managed cache/);
  assert.match(validationDoc, /resources\\relay-tools\\ripgrep/);
  assert.match(validationDoc, /rg --version/);
  assert.match(validationDoc, /ripgrep, not slow grep\s+fallback/);
  assert.match(validationDoc, /representative capped\s+results/);
  assert.match(validationDoc, /not dominated by a single subfolder/);
  assert.match(validationDoc, /one deep\s+branch/);
  assert.match(validationDoc, /\/guid/);
  assert.match(validationDoc, /folder selection/);
  assert.match(validationDoc, /prompt examples/);
  assert.match(validationDoc, /primary search\/task CTA/);
  assert.match(validationDoc, /recent\/popular suggestions/);
  assert.match(validationDoc, /one real preset assistant\s+entry/);
  assert.match(validationDoc, /metadata-only search and summary\s+labels/);
  assert.match(validationDoc, /relay-document-search/);
  assert.match(validationDoc, /raw `glob`, `grep`, or `read`/);
  assert.match(validationDoc, /without forcing a tutorial/);
  assert.match(validationDoc, /provider\/model setup/);
  assert.match(validationDoc, /default visible settings tab/);
  assert.match(validationDoc, /Skills Market banner/);
  assert.match(validationDoc, /permission-mode selector/);
  assert.match(validationDoc, /assistant\s+preset add button/);
  assert.match(validationDoc, /auto-injected skills\s+submenu/);
  assert.match(validationDoc, /candidates-visible/);
  assert.match(validationDoc, /checking-file-contents/);
  assert.match(validationDoc, /confirmed-results/);
  assert.match(validationDoc, /query construction is Relay-owned/i);
  assert.match(validationDoc, /cannot change searched roots, budgets, confirmation policy, or coverage/);
  assert.match(validationDoc, /no-results/);
  assert.match(validationDoc, /broadening keywords/);
  assert.match(validationDoc, /actionable card/);
  assert.match(validationDoc, /use-as-evidence/);
  assert.match(validationDoc, /evidence-backed results/);
  assert.match(validationDoc, /AionUi's core UX/);
  assert.match(validationDoc, /SendBox `\/` command menu/);
  assert.match(validationDoc, /PreviewPanel/);
  assert.match(validationDoc, /relay\.advancedSurfaces\.enabled/);
  assert.match(validationDoc, /Officeファイルを編集する/);
  assert.match(validationDoc, /through OfficeCLI/);
});

test("signing docs point normal releases at the AionUi workflow and mark Tauri release as legacy", () => {
  assert.match(signingDoc, /release-aionui-windows-installer\.yml/);
  assert.match(signingDoc, /Relay-branded AionUi\s+installer/);
  assert.match(signingDoc, /legacy Tauri\/OpenCode diagnostic workflow/);
  assert.match(selfSignedDoc, /release-aionui-windows-installer\.yml/);
  assert.match(selfSignedDoc, /confirm_legacy_tauri_release=true/);
  assert.doesNotMatch(selfSignedDoc, /gh workflow run release-windows-installer\.yml/);
});
